import { GoogleGenAI } from "@google/genai";

export type FeelingsType = {
  name: string;
  emoji: string;
  colorsGradient: string[];
};

export type InsightsType = {
  moodScore?: number;
  suggestedTags?: string[];
  growthAreas?: string[];
  positiveInsights?: string[];
  summary?: string;
  mainEmoji?: string;
  feelings?: FeelingsType[];
  title?: string;
  enrichedTranscript?: string;
  aiInsights?: string;
};

export const defaultInsights: InsightsType = {
  moodScore: 0,
  suggestedTags: [],
  growthAreas: [],
  positiveInsights: [],
  summary: "",
  mainEmoji: "",
  feelings: [],
  title: "",
  enrichedTranscript: "",
  aiInsights: "",
};
const ai = new GoogleGenAI({
  apiKey: "AIzaSyAx2xyv9nnK2-smi3YElqL48kQZQ8_EKBc",
});

export const getInsights = async (transcript: string) => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash",
      contents: `Here is a journal entry:\n\n${transcript}\n\n
      Analyze it and return insights in JSON format following the schema.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: "object",
          properties: {
            moodScore: {
              type: "integer",
              description:
                "Overall mood score between 1 (very negative) and 5 (very positive).",
            },
            suggestedTags: {
              type: "array",
              items: { type: "string" },
              description: "Keywords/tags that categorize this entry.",
            },
            growthAreas: {
              type: "array",
              items: { type: "string" },
              description:
                "Challenges, areas for self-reflection, or improvement.",
            },
            positiveInsights: {
              type: "array",
              items: { type: "string" },
              description:
                "Positive takeaways, gratitude points, or strengths.",
            },
            summary: {
              type: "string",
              description:
                "A short empathetic summary written directly to the user (e.g., 'You are feeling overwhelmed but also hopeful...').",
            },
            mainEmoji: {
              type: "string",
              enum: ["terrible", "bad", "fine", "good", "great"],
            },
            feelings: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  name: { type: "string" },
                  emoji: {
                    type: "string",
                    description: "Emoji representing the feeling.",
                  },
                  colorsGradient: {
                    type: "array",
                    items: {
                      type: "string",
                      description:
                        "Colors for the gradient background that represents the feeling of the tag chip. The first color is the top color and the second color is the bottom color.",
                    },
                  },
                },
                required: ["name", "emoji", "colorsGradient"],
              },
              description: "Different feelings expressed in the journal.",
            },
            title: {
              type: "string",
              description: "Add a short 'title' in a few words.",
            },
            enrichedTranscript: {
              type: "string",
              description:
                "The journal entry returned as a single string, but formatted with line breaks (\\n) between sentences or logical sections for readability, with emojis added where appropriate.",
            },
            aiInsights: {
              type: "string",
              description:
                "Deeper reflection generated by AI that highlights patterns, connections, or broader meaning behind the entry.",
            },
          },
          required: [
            "moodScore",
            "suggestedTags",
            "growthAreas",
            "positiveInsights",
            "summary",
            "mainEmoji",
            "feelings",
            "enrichedTranscript",
            "aiInsights",
          ],
        },
      },
    });

    if (!response.text) return defaultInsights;
    const insights: InsightsType = JSON.parse(response.text);
    return insights;
  } catch (error) {
    console.error("Error getting insights:", error);
    return defaultInsights;
  }
};

// config: {
//     responseMimeType: "application/json",
//     responseSchema: {
//       type: "array",
//       items: {
//         type: "object",
//         properties: {
//           recipeName: { type: "string" },
//           ingredients: { type: "array", items: { type: "string" } },
//         },
//         required: ["recipeName", "ingredients"],
//       },
//     },
//   },
