import { StyleSheet } from "react-native";

export const nutrieStyles = StyleSheet.create({
  screenBg: { flex: 1, backgroundColor: "#FFFFFF" },
  statRow: { flexDirection: "row", gap: 12, marginBottom: 24, paddingHorizontal: 4 },
  statCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.03)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 2,
    alignItems: "center",
  },
  statBadge: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, marginBottom: 12 },
  statBadgeText: { fontSize: 12, fontWeight: "700", letterSpacing: 0.2 },
  statValueRow: { flexDirection: "row", alignItems: "baseline", gap: 4, marginBottom: 12 },
  statValue: { fontSize: 28, fontWeight: "800", color: "#1C1C1E", letterSpacing: -0.5 },
  statUnit: { fontSize: 14, fontWeight: "600", color: "#8E8E93" },
  sectionHeader: { flexDirection: "row", alignItems: "center", marginBottom: 10, paddingHorizontal: 0, gap: 8 },
  jumpBackInHeader: { paddingTop: 16, marginBottom: 2 },
  jumpBackInTitle: { color: "#1C1C1E", fontSize: 20, fontWeight: "800", letterSpacing: -0.3 },
  jumpBackInSubtitle: { color: "#77777E", fontSize: 13, marginTop: 3 },
  categoryBadge: { flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  categoryBadgeText: { fontSize: 15, fontWeight: "800", letterSpacing: -0.2 },
  cleanSectionTitle: { fontSize: 18, fontWeight: "800", color: "#142414", letterSpacing: -0.3 },
  countBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  countBadgeText: { fontSize: 12, fontWeight: "700" },
  sectionDescription: { fontSize: 15, color: "#636366", marginBottom: 16, paddingHorizontal: 0, lineHeight: 22 },
  exerciseCard: { backgroundColor: "#FFFFFF", borderRadius: 16, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: "rgba(0,0,0,0.06)" },
  exerciseIconWell: { alignItems: "center", justifyContent: "center", borderRadius: 12, width: 48, height: 48 },
  exerciseTitle: { fontSize: 17, fontWeight: "800", color: "#1C1C1E", letterSpacing: -0.4, lineHeight: 22, marginBottom: 4 },
  exerciseSubtitle: { fontSize: 14, color: "#636366", lineHeight: 20 },
  inlinePill: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 6, paddingVertical: 4, borderRadius: 6, backgroundColor: "#F4F4F5" },
  inlinePillText: { fontSize: 12, fontWeight: "500", color: "#636366" },
  arrowWell: { width: 32, height: 32, borderRadius: 16, backgroundColor: "#F4F4F5", alignItems: "center", justifyContent: "center" },
  logCard: { backgroundColor: "#FFFFFF", borderRadius: 16, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: "rgba(0,0,0,0.06)" },
  logIconWell: { width: 48, height: 48, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  logHeading: { fontSize: 12, fontWeight: "700", color: "#636366", letterSpacing: 0.5, textTransform: "uppercase" },
  logDate: { fontSize: 12, color: "#636366", fontWeight: "500" },
  logTitle: { fontSize: 16, fontWeight: "600", color: "#1C1C1E", letterSpacing: -0.2 },
});
