-- Auto-generated by src/scripts/seedGen — do not hand-edit.
-- Regenerate via: npx jest --config jest.config.seedgen.js src/scripts/seedGen/emit.test.ts
BEGIN;

ALTER TABLE courses ADD COLUMN IF NOT EXISTS domain TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS target_audience TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS total_lessons INT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS total_duration_weeks INT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS sessions_per_week INT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS session_duration_minutes INT[];

ALTER TABLE sections ADD COLUMN IF NOT EXISTS narrative_hook TEXT;
ALTER TABLE sections ADD COLUMN IF NOT EXISTS badge_on_complete TEXT;
ALTER TABLE sections ADD COLUMN IF NOT EXISTS difficulty_range NUMERIC[];
ALTER TABLE sections ADD COLUMN IF NOT EXISTS objectives JSONB NOT NULL DEFAULT '{}';
ALTER TABLE sections ADD COLUMN IF NOT EXISTS concepts_introduced TEXT[] NOT NULL DEFAULT '{}';

ALTER TABLE nodes ADD COLUMN IF NOT EXISTS icon TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS new_concepts TEXT[];
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS review_concepts TEXT[];
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS prerequisites TEXT[];

ALTER TABLE nodes DROP CONSTRAINT IF EXISTS nodes_type_check;
ALTER TABLE nodes ADD CONSTRAINT nodes_type_check
  CHECK (type IN ('lesson', 'story', 'quiz', 'exercise', 'practice', 'challenge', 'boss', 'mood_check', 'journal', 'checkpoint', 'chest', 'trophy', 'ai_insight'));

CREATE TABLE IF NOT EXISTS exercises (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  node_id UUID NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  order_index INT NOT NULL DEFAULT 0,
  type TEXT NOT NULL,
  phase TEXT,
  duration_seconds INT,
  scaffold_level INT,
  difficulty NUMERIC,
  is_scored BOOLEAN NOT NULL DEFAULT false,
  concept TEXT,
  content JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (node_id, order_index)
);
CREATE INDEX IF NOT EXISTS exercises_node_id_idx ON exercises(node_id);
ALTER TABLE exercises ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS exercises_read_all ON exercises;
CREATE POLICY exercises_read_all ON exercises FOR SELECT USING (true);
GRANT SELECT ON exercises TO authenticated, anon;

CREATE OR REPLACE FUNCTION pg_temp.seed_uuid(seed_value TEXT)
RETURNS UUID LANGUAGE SQL IMMUTABLE STRICT AS $function$
  SELECT (
    substr(md5(seed_value), 1, 8) || '-' || substr(md5(seed_value), 9, 4) || '-' ||
    substr(md5(seed_value), 13, 4) || '-' || substr(md5(seed_value), 17, 4) || '-' ||
    substr(md5(seed_value), 21, 12)
  )::uuid;
$function$;

CREATE OR REPLACE FUNCTION pg_temp.text_array(input_json JSONB)
RETURNS TEXT[] LANGUAGE SQL IMMUTABLE AS $function$
  SELECT COALESCE(ARRAY(SELECT jsonb_array_elements_text(COALESCE(input_json, '[]'::jsonb))), '{}'::text[]);
$function$;

CREATE OR REPLACE FUNCTION pg_temp.numeric_array(input_json JSONB)
RETURNS NUMERIC[] LANGUAGE SQL IMMUTABLE AS $function$
  SELECT COALESCE(ARRAY(SELECT value::numeric FROM jsonb_array_elements_text(COALESCE(input_json, '[]'::jsonb))), '{}'::numeric[]);
$function$;

INSERT INTO courses (id, title, description, icon_url, color_hex, order_index, is_published, domain, target_audience, total_lessons, total_duration_weeks, sessions_per_week, session_duration_minutes)
SELECT pg_temp.seed_uuid(r.source_id), r.title, r.description, r.icon_url, r.color_hex, r.order_index, r.is_published, r.domain, r.target_audience, r.total_lessons, r.total_duration_weeks, r.sessions_per_week, pg_temp.text_array(r.session_duration_minutes)::INT[]
FROM jsonb_to_recordset($tag$[
  {
    "source_id": "stress-steady-under-pressure",
    "title": "Steady Under Pressure",
    "description": "By the end, the learner can explain why the stress response exists and what it runs on, recognize their own tells that it has tipped, read their appraisal of a stressor and choose the coping strategy that fits, reach the parasympathetic brake directly with a practiced body tool, and sustain the practice through recovery, support, and a rehearsed maintenance commitment.",
    "icon_url": null,
    "color_hex": "6B8F71",
    "order_index": 1,
    "is_published": false,
    "domain": "stress_resilience",
    "target_audience": "Adults dealing with everyday or work-related stress — not diagnosed anxiety, depression, or clinical burnout",
    "total_lessons": 63,
    "total_duration_weeks": null,
    "sessions_per_week": null,
    "session_duration_minutes": [
      5,
      15
    ]
  }
]$tag$::jsonb) AS r(
  source_id text, title text, description text, icon_url text, color_hex text, order_index int, is_published boolean,
  domain text, target_audience text, total_lessons int, total_duration_weeks int, sessions_per_week int, session_duration_minutes jsonb
)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, icon_url = EXCLUDED.icon_url, color_hex = EXCLUDED.color_hex, order_index = EXCLUDED.order_index, is_published = EXCLUDED.is_published, domain = EXCLUDED.domain, target_audience = EXCLUDED.target_audience, total_lessons = EXCLUDED.total_lessons, total_duration_weeks = EXCLUDED.total_duration_weeks, sessions_per_week = EXCLUDED.sessions_per_week, session_duration_minutes = EXCLUDED.session_duration_minutes;

INSERT INTO sections (id, course_id, title, order_index, narrative_hook, badge_on_complete, difficulty_range, objectives, concepts_introduced)
SELECT pg_temp.seed_uuid(r.source_id), pg_temp.seed_uuid(r.course_source_id), r.title, r.order_index, r.narrative_hook, r.badge_on_complete, pg_temp.numeric_array(r.difficulty_range), r.objectives, pg_temp.text_array(r.concepts_introduced)
FROM jsonb_to_recordset($tag$[
  {
    "source_id": "stress-steady-under-pressure-s2",
    "course_source_id": "stress-steady-under-pressure",
    "title": "Calming Your Body",
    "order_index": 1,
    "narrative_hook": "You can't out-think a body that's already mobilized. This section reaches the brake directly.",
    "badge_on_complete": "Steady Hands",
    "difficulty_range": [
      0.3,
      0.55
    ],
    "objectives": {
      "remember": "Name the general mechanism behind slow breathing (longer exhale → vagal stimulation) and the tense-release contrast that PMR teaches",
      "understand": "Explain why mindful noticing means catching a wandering mind and returning without self-criticism, and why exercise buffers the NEXT stressor rather than fixing the current one",
      "apply": "Choose and use a breathing pattern, a tension-release check, or a movement practice under real time pressure, matched to the moment"
    },
    "concepts_introduced": [
      "slow_breathing_general",
      "progressive_muscle_relaxation",
      "mindful_noticing",
      "exercise_as_stress_buffer"
    ]
  }
]$tag$::jsonb) AS r(
  source_id text, course_source_id text, title text, order_index int, narrative_hook text, badge_on_complete text,
  difficulty_range jsonb, objectives jsonb, concepts_introduced jsonb
)
ON CONFLICT (id) DO UPDATE SET course_id = EXCLUDED.course_id, title = EXCLUDED.title, order_index = EXCLUDED.order_index, narrative_hook = EXCLUDED.narrative_hook, badge_on_complete = EXCLUDED.badge_on_complete, difficulty_range = EXCLUDED.difficulty_range, objectives = EXCLUDED.objectives, concepts_introduced = EXCLUDED.concepts_introduced;

INSERT INTO units (id, section_id, title, icon_key, order_index)
SELECT pg_temp.seed_uuid(r.source_id), pg_temp.seed_uuid(r.section_source_id), r.title, r.icon_key, r.order_index
FROM jsonb_to_recordset($tag$[
  {
    "source_id": "stress-steady-under-pressure-s2-u1",
    "section_source_id": "stress-steady-under-pressure-s2",
    "title": "Breathing as a Direct Lever",
    "icon_key": "default",
    "order_index": 0
  },
  {
    "source_id": "stress-steady-under-pressure-s2-u2",
    "section_source_id": "stress-steady-under-pressure-s2",
    "title": "Releasing the Body's Tension",
    "icon_key": "default",
    "order_index": 1
  },
  {
    "source_id": "stress-steady-under-pressure-s2-u3",
    "section_source_id": "stress-steady-under-pressure-s2",
    "title": "Movement and Your Whole Toolkit",
    "icon_key": "default",
    "order_index": 2
  }
]$tag$::jsonb) AS r(source_id text, section_source_id text, title text, icon_key text, order_index int)
ON CONFLICT (id) DO UPDATE SET section_id = EXCLUDED.section_id, title = EXCLUDED.title, icon_key = EXCLUDED.icon_key, order_index = EXCLUDED.order_index;

INSERT INTO nodes (id, unit_id, title, type, content_id, content_type, pass_threshold, order_index, estimated_mins, icon, new_concepts, review_concepts, prerequisites)
SELECT pg_temp.seed_uuid(r.source_id), pg_temp.seed_uuid(r.unit_source_id), r.title, r.type, NULL, NULL, r.pass_threshold, r.order_index, r.estimated_mins, r.icon, pg_temp.text_array(r.new_concepts), pg_temp.text_array(r.review_concepts), pg_temp.text_array(r.prerequisites)
FROM jsonb_to_recordset($tag$[
  {
    "source_id": "stress-steady-under-pressure-l27",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Why Slow Breathing Works At All",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 0,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l28",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Practice: Five Minutes, Five Days",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 1,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l29",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Box Breathing, In Practice",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 2,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l30",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Which Breath, Which Moment",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 3,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l31",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Breath Under Real Pressure",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 4,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l32",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Unit Checkpoint: Breath as a Tool",
    "type": "checkpoint",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 5,
    "estimated_mins": 3,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l33",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "Tense, Then Notice the Release",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 0,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l34",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "Noticing Without Fixing",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 1,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l35",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "When Your Mind Wanders, That's the Practice",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 2,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l36",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "A Body Scan in Three Zones",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 3,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l37",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "Tension You Didn't Notice You Were Holding",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 4,
    "estimated_mins": 1,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l38",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "Unit Checkpoint: Release and Notice",
    "type": "checkpoint",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 5,
    "estimated_mins": 3,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l39",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Finish the Mobilization: Move",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 0,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l40",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Ten Minutes Counts",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 1,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l41",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Build Your Body Toolkit",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 2,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l42",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Which Tool, Which Moment (Review)",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 3,
    "estimated_mins": 1,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l43",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Your Body's Signals, Revisited",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 4,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l44",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Section 2 Checkpoint",
    "type": "checkpoint",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 5,
    "estimated_mins": 4,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  }
]$tag$::jsonb) AS r(
  source_id text, unit_source_id text, title text, type text, content_id text, content_type text,
  pass_threshold int, order_index int, estimated_mins int, icon text, new_concepts jsonb, review_concepts jsonb, prerequisites jsonb
)
ON CONFLICT (id) DO UPDATE SET unit_id = EXCLUDED.unit_id, title = EXCLUDED.title, type = EXCLUDED.type, content_id = EXCLUDED.content_id, content_type = EXCLUDED.content_type, pass_threshold = EXCLUDED.pass_threshold, order_index = EXCLUDED.order_index, estimated_mins = EXCLUDED.estimated_mins, icon = EXCLUDED.icon, new_concepts = EXCLUDED.new_concepts, review_concepts = EXCLUDED.review_concepts, prerequisites = EXCLUDED.prerequisites;

INSERT INTO exercises (id, node_id, order_index, type, phase, duration_seconds, scaffold_level, difficulty, is_scored, concept, content)
SELECT pg_temp.seed_uuid(r.source_id), pg_temp.seed_uuid(r.node_source_id), r.order_index, r.type, r.phase, r.duration_seconds, r.scaffold_level, r.difficulty, r.is_scored, r.concept, r.content
FROM jsonb_to_recordset($tag$[
  {
    "source_id": "stress-steady-under-pressure-l27-l27-e1",
    "node_source_id": "stress-steady-under-pressure-l27",
    "order_index": 0,
    "type": "concept_card",
    "phase": "teach",
    "duration_seconds": 35,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": "slow_breathing_general",
    "content": {
      "title": "The Exhale Is The Lever, Not The Count",
      "variant": "myth",
      "myth": "Only one specific breathing ratio works; the exact count matters more than the pace.",
      "reality": "Any slow breath with a longer exhale reaches the parasympathetic brake through the vagus nerve. Cyclic sighing and box breathing look different — one has two inhales, one has equal counts — but both work because of the same thing: a slow pace with a real exhale."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l27-l27-e2",
    "node_source_id": "stress-steady-under-pressure-l27",
    "order_index": 1,
    "type": "intuition_check",
    "phase": "practice",
    "duration_seconds": 25,
    "scaffold_level": 2,
    "difficulty": 0.21,
    "is_scored": true,
    "concept": "slow_breathing_general",
    "content": {
      "prompt": "The specific count in box breathing (4-4-4-4) — is that what makes it work?",
      "options": [
        {
          "id": "no",
          "label": "No — the slow pace and real exhale are the active ingredient"
        },
        {
          "id": "yes",
          "label": "Yes — the exact count matters more than the pace"
        }
      ],
      "bestOptionId": "no",
      "reveal": "The count is a structure to hold attention, not the active ingredient — a longer exhale is what stimulates the vagus nerve."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l27-l27-e3",
    "node_source_id": "stress-steady-under-pressure-l27",
    "order_index": 2,
    "type": "same_but_different",
    "phase": "apply",
    "duration_seconds": 30,
    "scaffold_level": 3,
    "difficulty": 0.32,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Same Lever, Different Structure",
      "leftHeading": "Cyclic Sighing",
      "rightHeading": "Box Breathing",
      "rows": [
        {
          "left": "Two inhales, one long exhale",
          "right": "Equal counts: in, hold, out, hold"
        },
        {
          "left": "No fixed count needed",
          "right": "A fixed count to hold attention"
        },
        {
          "left": "Same mechanism: long exhale → vagus",
          "right": "Same mechanism: long exhale → vagus"
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l27-l27-e4",
    "node_source_id": "stress-steady-under-pressure-l27",
    "order_index": 3,
    "type": "why_it_matters",
    "phase": "close",
    "duration_seconds": 30,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Recognize It Anywhere",
      "instruction": "Read, then move on.",
      "message": "Any new breathing pattern you encounter anywhere — a slow pace with a real exhale — is this same lever.",
      "explanation": "You don't need to learn a new mechanism for every new pattern; you just need to recognize the one you already know."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l28-l28-e1",
    "node_source_id": "stress-steady-under-pressure-l28",
    "order_index": 0,
    "type": "intuition_check",
    "phase": "review",
    "duration_seconds": 25,
    "scaffold_level": 2,
    "difficulty": 0.21,
    "is_scored": true,
    "concept": "slow_breathing_general",
    "content": {
      "prompt": "What's the active ingredient in any slow breathing technique?",
      "options": [
        {
          "id": "exhale",
          "label": "A slow pace with a real, longer exhale"
        },
        {
          "id": "count",
          "label": "Hitting the exact count precisely"
        }
      ],
      "bestOptionId": "exhale",
      "reveal": "The exhale is the active ingredient — the count is just a structure to hold onto."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l28-l28-e2",
    "node_source_id": "stress-steady-under-pressure-l28",
    "order_index": 1,
    "type": "why_it_matters",
    "phase": "close",
    "duration_seconds": 30,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "The Real Dose",
      "instruction": "Read, then practice.",
      "message": "The study that found cyclic sighing beat meditation on mood used five minutes a day for a month — not five minutes once.",
      "explanation": "Today's practice is the first of those five minutes. A technique tried once and never again isn't the technique that was actually studied."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l28-l28-e3",
    "node_source_id": "stress-steady-under-pressure-l28",
    "order_index": 2,
    "type": "breathing_round",
    "phase": "close",
    "duration_seconds": 50,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": "slow_breathing_general",
    "content": {
      "title": "Today's Five Minutes",
      "instruction": "Two inhales, one long exhale. Repeat for about five minutes, at your own pace."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l29-l29-e1",
    "node_source_id": "stress-steady-under-pressure-l29",
    "order_index": 0,
    "type": "concept_card",
    "phase": "teach",
    "duration_seconds": 35,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "A Count To Hold Onto",
      "variant": "rule",
      "rule": "Box breathing: inhale 4, hold 4, exhale 4, hold 4 — a countable structure for a moment that needs one, like a wait before a hard conversation.",
      "explanation": "Skip the holds — breathe slowly without pausing — if you're pregnant, have a heart or blood-pressure condition, or holding your breath makes you dizzy or anxious. The slow pace is what matters; the hold is optional, and skipping it is the correct choice for those learners."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l29-l29-e2",
    "node_source_id": "stress-steady-under-pressure-l29",
    "order_index": 1,
    "type": "breathing_round",
    "phase": "close",
    "duration_seconds": 50,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Try It Now",
      "instruction": "Four in, four hold (or skip the hold and just breathe slowly), four out, four hold. Repeat for a minute or two."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l29-l29-e3",
    "node_source_id": "stress-steady-under-pressure-l29",
    "order_index": 2,
    "type": "reflection_choice",
    "phase": "close",
    "duration_seconds": 20,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "How did that land?",
      "options": [
        {
          "id": "helped",
          "label": "The count gave my mind somewhere to go"
        },
        {
          "id": "skipped-hold",
          "label": "I skipped the hold, and that was the right call for me"
        },
        {
          "id": "prefer-cyclic",
          "label": "I still prefer the cyclic sighing pattern"
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l30-l30-e1",
    "node_source_id": "stress-steady-under-pressure-l30",
    "order_index": 0,
    "type": "fill_blank",
    "phase": "review",
    "duration_seconds": 30,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": true,
    "concept": "slow_breathing_general",
    "content": {
      "title": "The Mechanism, Again",
      "instruction": "Fill in the blank.",
      "variants": [
        {
          "pre": "Any slow breathing technique works through the same lever — a longer ___",
          "post": " stimulating the vagus nerve.",
          "answers": [
            "exhale"
          ],
          "correctFeedback": "Right — the exhale, not the specific pattern, is the mechanism.",
          "incorrectFeedback": "It's the longer exhale that stimulates the vagus nerve, regardless of the specific pattern.",
          "workedExample": "Cyclic sighing and box breathing both work through this same exhale-vagus mechanism."
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l30-l30-e2",
    "node_source_id": "stress-steady-under-pressure-l30",
    "order_index": 1,
    "type": "lever_match",
    "phase": "apply",
    "duration_seconds": 35,
    "scaffold_level": 3,
    "difficulty": 0.32,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Which Breath, Which Moment",
      "instruction": "Match each moment to the breath that fits it best.",
      "pairs": [
        {
          "id": "alone",
          "left": "Alone, just need to come down",
          "right": "Cyclic sighing"
        },
        {
          "id": "waiting",
          "left": "Waiting outside a room you don't want to walk into",
          "right": "Box breathing"
        }
      ],
      "clue": "One needs nothing but calm; the other needs a count to hold attention.",
      "feedbackTitle": "TWO TOOLS, ONE MECHANISM",
      "feedback": "Cyclic sighing when nothing else is needed; box breathing when a countable structure helps hold attention through a wait."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l30-l30-e3",
    "node_source_id": "stress-steady-under-pressure-l30",
    "order_index": 2,
    "type": "why_it_matters",
    "phase": "close",
    "duration_seconds": 30,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Two Tools, One Choosing Rule",
      "instruction": "Read, then move on.",
      "message": "Cyclic sighing when nothing else is needed but calm. Box breathing when a countable structure helps hold attention through a wait.",
      "explanation": "Two tools without a rule for choosing between them just sit unused — now you have the rule."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l31-l31-e1",
    "node_source_id": "stress-steady-under-pressure-l31",
    "order_index": 0,
    "type": "reframe_builder",
    "phase": "review",
    "duration_seconds": 50,
    "scaffold_level": 5,
    "difficulty": 0.54,
    "is_scored": true,
    "concept": "slow_breathing_general",
    "content": {
      "title": "Which Breath, Under Pressure",
      "instruction": "Choose one phrase at a time.",
      "hotThought": "A flight delay just became a missed connection — there's no time to think about breathing.",
      "trays": [
        {
          "id": "fits",
          "slotLabel": "What fits here",
          "options": [
            {
              "id": "box",
              "label": "Box breathing — a count to hold attention"
            },
            {
              "id": "nothing",
              "label": "Nothing — breathing doesn't help under real pressure"
            }
          ]
        },
        {
          "id": "why",
          "slotLabel": "Why",
          "options": [
            {
              "id": "structure",
              "label": "the escalating stress is exactly when a countable structure helps most"
            },
            {
              "id": "useless",
              "label": "breathing only works when already calm"
            }
          ]
        }
      ],
      "joinStrategy": {
        "type": "template",
        "template": "{fits} — {why}."
      },
      "comparisonFeedback": "The mechanism works under real pressure — that's the actual use case, not a nice-to-have for calm moments only."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l31-l31-e2",
    "node_source_id": "stress-steady-under-pressure-l31",
    "order_index": 1,
    "type": "invent_first",
    "phase": "apply",
    "duration_seconds": 50,
    "scaffold_level": 6,
    "difficulty": 0.65,
    "is_scored": true,
    "concept": null,
    "content": {
      "title": "Breath Under Real Pressure",
      "instruction": "Read each stage, then pick the breath that fits.",
      "question": "Stage 1: a flight delay, mildly annoying. Stage 2: a gate change with a tight connection. Stage 3: the connection is now missed. At stage 3, which breath?",
      "cases": [
        {
          "id": "s1",
          "name": "Stage 1",
          "text": "A flight delay — mildly annoying, nothing urgent yet.",
          "label": "Stage 1"
        },
        {
          "id": "s2",
          "name": "Stage 2",
          "text": "A gate change with a tight connection — arousal rising.",
          "label": "Stage 2"
        },
        {
          "id": "s3",
          "name": "Stage 3",
          "text": "The connection is now missed — arousal is high, thinking is hard.",
          "label": "Stage 3"
        }
      ],
      "options": [
        {
          "id": "box",
          "label": "Box breathing — a count to hold attention while rebooking"
        },
        {
          "id": "none",
          "label": "No breath needed — just start rebooking immediately"
        }
      ],
      "feedbackMap": {
        "box": {
          "title": "Right",
          "body": "At the highest-arousal stage, a countable structure gives your attention somewhere to go before you try to think clearly about rebooking.",
          "chain": [
            "Arousal is now high.",
            "Thinking clearly is harder at this level.",
            "A structured breath first makes the next step easier."
          ]
        },
        "none": {
          "title": "Not quite",
          "body": "Skipping the breath at the highest-arousal point makes the next steps harder to think through, not easier.",
          "chain": [
            "High arousal makes clear thinking harder, not easier."
          ],
          "counterTitle": "Try the arousal angle",
          "counterBody": "Ask what arousal level makes a lever most useful, not least."
        }
      }
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l32-l32-e1",
    "node_source_id": "stress-steady-under-pressure-l32",
    "order_index": 0,
    "type": "fill_blank",
    "phase": "review",
    "duration_seconds": 30,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": true,
    "concept": "slow_breathing_general",
    "content": {
      "title": "The Mechanism, Once More",
      "instruction": "Fill in the blank.",
      "variants": [
        {
          "pre": "Both cyclic sighing and box breathing work through the same ___",
          "post": " — a longer exhale reaching the vagus nerve.",
          "answers": [
            "mechanism"
          ],
          "correctFeedback": "Right — one mechanism, two structures.",
          "incorrectFeedback": "It's the same mechanism underneath both patterns.",
          "workedExample": "Different counts, same lever."
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l32-l32-e2",
    "node_source_id": "stress-steady-under-pressure-l32",
    "order_index": 1,
    "type": "teach_back_chain",
    "phase": "review",
    "duration_seconds": 55,
    "scaffold_level": 5,
    "difficulty": 0.54,
    "is_scored": true,
    "concept": "slow_breathing_general",
    "content": {
      "title": "The Shared Logic",
      "instruction": "Order the sequence, then apply it.",
      "message": "Both patterns follow the same underlying chain.",
      "steps": [
        {
          "id": "slow",
          "label": "Slow the pace of breathing",
          "order": 1
        },
        {
          "id": "exhale",
          "label": "Extend the exhale",
          "order": 2
        },
        {
          "id": "vagus",
          "label": "Vagus nerve is stimulated",
          "order": 3
        },
        {
          "id": "brake",
          "label": "Balance shifts toward the parasympathetic brake",
          "order": 4
        }
      ],
      "transfer": {
        "prompt": "A new breathing app teaches a 'triangle breath' — inhale, hold, exhale, no second hold. Does the same mechanism apply?",
        "options": [
          {
            "id": "yes",
            "label": "Yes — it still has a slow pace with a real exhale",
            "isSupported": true,
            "response": "Right — any new pattern with a slow pace and a real exhale is this same lever, whatever it's branded as.",
            "takeaway": "You can recognize a new pattern as this mechanism without ever having seen its name before."
          },
          {
            "id": "no",
            "label": "No — it's a different technique entirely",
            "isSupported": false,
            "response": "Not quite — the shape differs, but the mechanism (slow pace, real exhale) is the same one.",
            "takeaway": "Different branding, same underlying lever."
          }
        ]
      }
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l32-l32-e3",
    "node_source_id": "stress-steady-under-pressure-l32",
    "order_index": 2,
    "type": "invent_first",
    "phase": "review",
    "duration_seconds": 50,
    "scaffold_level": 6,
    "difficulty": 0.65,
    "is_scored": true,
    "concept": "slow_breathing_general",
    "content": {
      "title": "A Pattern You've Never Seen Named",
      "instruction": "Read the case, then decide.",
      "question": "A coach tells an athlete to inhale for 3 counts and exhale for 6, repeated before a big moment. Does this fit the lever you've learned?",
      "cases": [
        {
          "id": "case1",
          "name": "The 3-6 pattern",
          "text": "Inhale for 3, exhale for 6, repeated before a big moment.",
          "label": "The Case"
        }
      ],
      "options": [
        {
          "id": "yes",
          "label": "Yes — the exhale is twice the inhale, a real longer exhale"
        },
        {
          "id": "no",
          "label": "No — it's not one of the two patterns taught in this course"
        }
      ],
      "feedbackMap": {
        "yes": {
          "title": "Right",
          "body": "A longer exhale relative to the inhale is exactly the mechanism — this pattern qualifies even though it was never named in this course.",
          "chain": [
            "Exhale (6) is longer than inhale (3).",
            "That's the exhale-vagus mechanism.",
            "It qualifies as this lever."
          ]
        },
        "no": {
          "title": "Not quite",
          "body": "The lever isn't defined by matching one of two named patterns — it's defined by a slow pace with a real, longer exhale, which this pattern has.",
          "chain": [
            "The mechanism generalizes beyond the two named patterns."
          ],
          "counterTitle": "Try the mechanism angle",
          "counterBody": "Ask whether the exhale is meaningfully longer than the inhale here."
        }
      }
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l32-l32-e4",
    "node_source_id": "stress-steady-under-pressure-l32",
    "order_index": 3,
    "type": "course_checkpoint",
    "phase": "checkpoint",
    "duration_seconds": 50,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Breath as a Tool — Checkpoint",
      "introTitle": "Let's see what's solid.",
      "intro": "Three quick checks on the breathing lever.\nA miss just gives you something to revisit.",
      "introTag": "3 QUESTIONS · ~1 MIN",
      "revisitMessage": "Worth a short revisit — nothing is lost, and it'll come back around.",
      "solidMessage": "The breathing lever is holding. Next: releasing tension the body's been holding onto.",
      "items": [
        {
          "concept": "Slow Breathing (General Mechanism)",
          "prompt": "What's the active ingredient in any slow breathing pattern?",
          "clue": "Not the count.",
          "worked": "A longer exhale, stimulating the vagus nerve — the count is just structure.",
          "options": [
            {
              "label": "A slow pace with a longer exhale",
              "feedback": "Right.",
              "isCorrect": true
            },
            {
              "label": "Matching the exact count precisely",
              "feedback": "The count is a structure to hold onto, not the active ingredient.",
              "isCorrect": false
            }
          ]
        },
        {
          "concept": "Cyclic Sighing vs. Box Breathing",
          "prompt": "When does box breathing's countable structure help most?",
          "clue": "Think about a wait.",
          "worked": "A wait before something hard — the count gives attention somewhere to go.",
          "options": [
            {
              "label": "A moment needing a countable structure to hold attention",
              "feedback": "Right.",
              "isCorrect": true
            },
            {
              "label": "Only when completely alone and calm",
              "feedback": "Cyclic sighing fits that moment better — box breathing is for structured waits.",
              "isCorrect": false
            }
          ]
        },
        {
          "concept": "Recognizing New Patterns",
          "prompt": "A brand-new breathing pattern you've never heard named — how do you know if it's this same lever?",
          "clue": "Check the exhale, not the name.",
          "worked": "If it has a slow pace and a real, longer exhale, it's this mechanism, regardless of its name.",
          "options": [
            {
              "label": "Check whether it has a slow pace and a longer exhale",
              "feedback": "Right.",
              "isCorrect": true
            },
            {
              "label": "Only patterns taught by name in this course count",
              "feedback": "The mechanism generalizes beyond any two named patterns.",
              "isCorrect": false
            }
          ]
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l33-l33-e1",
    "node_source_id": "stress-steady-under-pressure-l33",
    "order_index": 0,
    "type": "concept_card",
    "phase": "teach",
    "duration_seconds": 35,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": "progressive_muscle_relaxation",
    "content": {
      "title": "The Contrast Is The Point",
      "variant": "myth",
      "myth": "Relaxation is just 'not being tense' — there's nothing to actually practice.",
      "reality": "Tensing a muscle on purpose, then releasing it completely, teaches what release actually feels like — many chronically tense people have lost the ability to notice tension building on its own. Don't tense any area that's injured, in pain, or recently operated on — skip that group entirely. Tense gently; the point is noticing the contrast, not squeezing hard."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l33-l33-e2",
    "node_source_id": "stress-steady-under-pressure-l33",
    "order_index": 1,
    "type": "breathing_round",
    "phase": "close",
    "duration_seconds": 50,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": "progressive_muscle_relaxation",
    "content": {
      "title": "Try It Now",
      "instruction": "Clench your shoulders toward your ears for five seconds, then let go completely. Repeat with your hands (make a fist), then your jaw (clench gently). Notice the drop after each release."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l33-l33-e3",
    "node_source_id": "stress-steady-under-pressure-l33",
    "order_index": 2,
    "type": "one_line_reveal",
    "phase": "practice",
    "duration_seconds": 25,
    "scaffold_level": 3,
    "difficulty": 0.32,
    "is_scored": true,
    "concept": null,
    "content": {
      "title": "What You Just Practiced",
      "instruction": "Complete the line, then check it.",
      "firstLine": "The drop you felt right after releasing is what ___ actually feels like.",
      "options": [
        {
          "id": "a",
          "label": "release",
          "isCorrect": true,
          "feedback": "Right — most people can't name that feeling until they've felt it taken away and come back."
        },
        {
          "id": "b",
          "label": "failure",
          "isCorrect": false,
          "feedback": "That drop is release, not a sign anything went wrong."
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l34-l34-e1",
    "node_source_id": "stress-steady-under-pressure-l34",
    "order_index": 0,
    "type": "reframe_builder",
    "phase": "review",
    "duration_seconds": 50,
    "scaffold_level": 5,
    "difficulty": 0.54,
    "is_scored": true,
    "concept": "slow_breathing_general",
    "content": {
      "title": "The Mechanism, Once More",
      "instruction": "Choose one phrase at a time.",
      "hotThought": "A friend's app teaches counting backward from 10 while breathing — that's not a real technique like the ones I learned.",
      "trays": [
        {
          "id": "check",
          "slotLabel": "What to check",
          "options": [
            {
              "id": "exhale",
              "label": "Whether the exhale is meaningfully longer than the inhale"
            },
            {
              "id": "name",
              "label": "Whether it has one of the two names taught"
            }
          ]
        },
        {
          "id": "so",
          "slotLabel": "So",
          "options": [
            {
              "id": "counts",
              "label": "if the exhale is longer, it counts as the same lever"
            },
            {
              "id": "doesnt",
              "label": "it doesn't count unless it's named the same"
            }
          ]
        }
      ],
      "joinStrategy": {
        "type": "template",
        "template": "{check} — {so}."
      },
      "comparisonFeedback": "The mechanism, not the branding, is what determines whether a pattern is this lever."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l34-l34-e2",
    "node_source_id": "stress-steady-under-pressure-l34",
    "order_index": 1,
    "type": "intuition_check",
    "phase": "review",
    "duration_seconds": 25,
    "scaffold_level": 2,
    "difficulty": 0.21,
    "is_scored": true,
    "concept": "progressive_muscle_relaxation",
    "content": {
      "prompt": "PMR's actual skill is noticing what?",
      "options": [
        {
          "id": "contrast",
          "label": "The contrast between tensed and released"
        },
        {
          "id": "relaxation",
          "label": "How to be maximally relaxed at all times"
        }
      ],
      "bestOptionId": "contrast",
      "reveal": "The contrast — feeling tension, then feeling it drop away — is what teaches you to recognize release."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l34-l34-e3",
    "node_source_id": "stress-steady-under-pressure-l34",
    "order_index": 2,
    "type": "concept_card",
    "phase": "teach",
    "duration_seconds": 35,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": "mindful_noticing",
    "content": {
      "title": "The Wandering Is Not The Failure",
      "variant": "myth",
      "myth": "If my mind wanders during a mindfulness exercise, I'm doing it wrong.",
      "reality": "Noticing attention wandering and gently coming back, without self-criticism, is the actual skill — not 'clearing the mind,' which isn't achievable on demand. A meditator with decades of practice still has a wandering mind; they've just gotten faster at noticing."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l34-l34-e4",
    "node_source_id": "stress-steady-under-pressure-l34",
    "order_index": 3,
    "type": "intuition_check",
    "phase": "practice",
    "duration_seconds": 25,
    "scaffold_level": 2,
    "difficulty": 0.21,
    "is_scored": true,
    "concept": "mindful_noticing",
    "content": {
      "prompt": "The goal of mindful noticing is to stop your mind from wandering — true or false?",
      "options": [
        {
          "id": "false",
          "label": "False — noticing the wander and returning is the skill"
        },
        {
          "id": "true",
          "label": "True — a wandering mind means it's not working"
        }
      ],
      "bestOptionId": "false",
      "reveal": "A wandering mind isn't a malfunction — noticing it and coming back, without judgment, is the entire practice."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l35-l35-e1",
    "node_source_id": "stress-steady-under-pressure-l35",
    "order_index": 0,
    "type": "one_line_reveal",
    "phase": "review",
    "duration_seconds": 25,
    "scaffold_level": 3,
    "difficulty": 0.32,
    "is_scored": true,
    "concept": "mindful_noticing",
    "content": {
      "title": "Quick Check",
      "instruction": "Complete the line, then check it.",
      "firstLine": "Noticing your mind wandered and coming back is a successful ___, not an interruption.",
      "options": [
        {
          "id": "a",
          "label": "rep of the skill",
          "isCorrect": true,
          "feedback": "Right — every wander-and-return is the practice working, not failing."
        },
        {
          "id": "b",
          "label": "sign of failure",
          "isCorrect": false,
          "feedback": "It's not a sign of failure — it's the skill happening exactly as designed."
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l35-l35-e2",
    "node_source_id": "stress-steady-under-pressure-l35",
    "order_index": 1,
    "type": "story_walkthrough",
    "phase": "teach",
    "duration_seconds": 35,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "The Most Common Early Mistake",
      "instruction": "Read through, then practice.",
      "beats": [
        {
          "id": "b1",
          "text": "You're two minutes into a guided practice, and you notice you've been thinking about dinner instead of your breath."
        },
        {
          "id": "b2",
          "text": "The instinct is to feel like you've failed the exercise — that a 'real' meditator wouldn't have wandered."
        },
        {
          "id": "b3",
          "text": "But noticing you drifted, right there, is the successful rep. Come back to the breath. No scorekeeping."
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l35-l35-e3",
    "node_source_id": "stress-steady-under-pressure-l35",
    "order_index": 2,
    "type": "breathing_round",
    "phase": "close",
    "duration_seconds": 50,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Try It, Expecting To Wander",
      "instruction": "Sit for two to three minutes, attention on your breath. When your mind wanders — and it will — just notice, and come back. That noticing is the whole practice."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l36-l36-e1",
    "node_source_id": "stress-steady-under-pressure-l36",
    "order_index": 0,
    "type": "fill_blank",
    "phase": "review",
    "duration_seconds": 30,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": true,
    "concept": "progressive_muscle_relaxation",
    "content": {
      "title": "The Contrast, Again",
      "instruction": "Fill in the blank.",
      "variants": [
        {
          "pre": "PMR teaches the ___ between tensing a muscle on purpose and releasing it completely,",
          "post": " which is what makes release noticeable again.",
          "answers": [
            "contrast"
          ],
          "correctFeedback": "Right — the contrast is what makes release recognizable.",
          "incorrectFeedback": "It's the contrast between tensed and released that's the actual skill.",
          "workedExample": "Clench, then let go — the drop after is what release feels like."
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l36-l36-e2",
    "node_source_id": "stress-steady-under-pressure-l36",
    "order_index": 1,
    "type": "story_walkthrough",
    "phase": "apply",
    "duration_seconds": 35,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Three Zones, One Pass",
      "instruction": "Read through, then practice.",
      "beats": [
        {
          "id": "b1",
          "text": "Zone 1 — head and shoulders: tense on purpose, then release. Notice the drop."
        },
        {
          "id": "b2",
          "text": "Zone 2 — torso and hands: just notice, no tensing. Whatever's there, without judging it."
        },
        {
          "id": "b3",
          "text": "Zone 3 — legs and feet: just notice again. A body scan is PMR's contrast plus mindful noticing's non-judgment, run together."
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l36-l36-e3",
    "node_source_id": "stress-steady-under-pressure-l36",
    "order_index": 2,
    "type": "breathing_round",
    "phase": "close",
    "duration_seconds": 50,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Try The Three Zones",
      "instruction": "Head and shoulders: tense, then release. Torso and hands: just notice. Legs and feet: just notice. No judging what you find."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l37-l37-e1",
    "node_source_id": "stress-steady-under-pressure-l37",
    "order_index": 0,
    "type": "guided_recall_chips",
    "phase": "review",
    "duration_seconds": 35,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": true,
    "concept": "mindful_noticing",
    "content": {
      "title": "Rebuild The Rule",
      "instruction": "Tap the chips in order to rebuild the rule.",
      "prompt": "The skill is noticing your attention ___ and coming back, without ___ yourself for it.",
      "chips": [
        "wandered",
        "criticizing",
        "cleared",
        "praising"
      ],
      "answer": [
        "wandered",
        "criticizing"
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l37-l37-e2",
    "node_source_id": "stress-steady-under-pressure-l37",
    "order_index": 1,
    "type": "private_check",
    "phase": "close",
    "duration_seconds": 25,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": "stress_signature",
    "content": {
      "title": "Tension You Didn't Notice",
      "instruction": "Take thirty seconds. Notice one place you're holding tension right now, without trying to fix it yet. Nothing here is stored or scored.",
      "items": [
        {
          "id": "check",
          "label": "Where do you notice something, right now?"
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l38-l38-e1",
    "node_source_id": "stress-steady-under-pressure-l38",
    "order_index": 0,
    "type": "fill_blank",
    "phase": "review",
    "duration_seconds": 30,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": true,
    "concept": null,
    "content": {
      "title": "Two Ideas, One Blank Each",
      "instruction": "Fill in the blank.",
      "variants": [
        {
          "pre": "PMR teaches the tense-release ___,",
          "post": " and mindful noticing means catching a wandering mind without judging it.",
          "answers": [
            "contrast"
          ],
          "correctFeedback": "Right — the contrast is the PMR skill; non-judgment is the noticing skill.",
          "incorrectFeedback": "PMR's skill is the tense-release contrast.",
          "workedExample": "A body scan combines both — contrast in one zone, plain noticing in the others."
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l38-l38-e2",
    "node_source_id": "stress-steady-under-pressure-l38",
    "order_index": 1,
    "type": "teach_back_chain",
    "phase": "review",
    "duration_seconds": 55,
    "scaffold_level": 5,
    "difficulty": 0.54,
    "is_scored": true,
    "concept": "progressive_muscle_relaxation",
    "content": {
      "title": "The Body Scan, In Order",
      "instruction": "Order the sequence, then apply it.",
      "message": "The scan combines both skills from this unit.",
      "steps": [
        {
          "id": "tense",
          "label": "Tense a muscle group on purpose",
          "order": 1
        },
        {
          "id": "release",
          "label": "Release completely, notice the drop",
          "order": 2
        },
        {
          "id": "notice",
          "label": "Move to the next zone, just notice, no tensing",
          "order": 3
        },
        {
          "id": "nojudge",
          "label": "Whatever's found, without judging it",
          "order": 4
        }
      ],
      "transfer": {
        "prompt": "You notice a tight jaw during a meeting, with no time for a full scan. What's the minimum version of this skill you could still use?",
        "options": [
          {
            "id": "one-zone",
            "label": "Tense and release just the jaw, once, right there",
            "isSupported": true,
            "response": "Right — the skill scales down to one zone, one contrast, wherever you are.",
            "takeaway": "You don't need the full three-zone version every time."
          },
          {
            "id": "skip",
            "label": "Skip it entirely — it only works as the full scan",
            "isSupported": false,
            "response": "Not quite — a single tense-release cycle on one muscle group still works.",
            "takeaway": "The contrast principle works at any scale."
          }
        ]
      }
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l38-l38-e3",
    "node_source_id": "stress-steady-under-pressure-l38",
    "order_index": 2,
    "type": "invent_first",
    "phase": "review",
    "duration_seconds": 50,
    "scaffold_level": 6,
    "difficulty": 0.65,
    "is_scored": true,
    "concept": "mindful_noticing",
    "content": {
      "title": "Wandering Somewhere New",
      "instruction": "Read the case, then decide.",
      "question": "Attention drifts away from a task at work, over and over, to an unrelated worry. Does the same 'notice and return, no judgment' skill apply here too?",
      "cases": [
        {
          "id": "case1",
          "name": "The drifting task",
          "text": "Attention keeps drifting from a work task to an unrelated worry, over and over.",
          "label": "The Case"
        }
      ],
      "options": [
        {
          "id": "yes",
          "label": "Yes — notice the drift, return to the task, without self-criticism"
        },
        {
          "id": "no",
          "label": "No — this skill only applies during formal meditation practice"
        }
      ],
      "feedbackMap": {
        "yes": {
          "title": "Right",
          "body": "The skill isn't limited to formal meditation — noticing a drift and returning without self-criticism works for a wandering mind anywhere, task-focus included.",
          "chain": [
            "Attention drifted from the task.",
            "Noticing it is a successful rep, not a failure.",
            "Return to the task, no scorekeeping."
          ]
        },
        "no": {
          "title": "Not quite",
          "body": "This skill generalizes well beyond formal meditation — any wandering-and-return moment is the same practice.",
          "chain": [
            "The mechanism (notice, return, no judgment) doesn't require a formal sitting practice."
          ],
          "counterTitle": "Try the generalization angle",
          "counterBody": "Ask what's actually required for this skill to apply — a breath, or the noticing itself?"
        }
      }
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l38-l38-e4",
    "node_source_id": "stress-steady-under-pressure-l38",
    "order_index": 3,
    "type": "course_checkpoint",
    "phase": "checkpoint",
    "duration_seconds": 50,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Release and Notice — Checkpoint",
      "introTitle": "Let's see what's solid.",
      "intro": "Two quick checks on this unit's tools.\nA miss just gives you something to revisit.",
      "introTag": "2 QUESTIONS · ~1 MIN",
      "revisitMessage": "Worth a short revisit — nothing is lost, and it'll come back around.",
      "solidMessage": "Release and notice are holding. Next: finishing the mobilization with movement, and your whole toolkit.",
      "items": [
        {
          "concept": "Progressive Muscle Relaxation",
          "prompt": "What's PMR's actual skill?",
          "clue": "Not just relaxing.",
          "worked": "The contrast between tensed and released — recognizing what release feels like.",
          "options": [
            {
              "label": "Noticing the tense-release contrast",
              "feedback": "Right.",
              "isCorrect": true
            },
            {
              "label": "Staying maximally relaxed at all times",
              "feedback": "The skill is the contrast, not constant relaxation.",
              "isCorrect": false
            }
          ]
        },
        {
          "concept": "Mindful Noticing",
          "prompt": "What should you do when your mind wanders during practice?",
          "clue": "No scorekeeping.",
          "worked": "Notice it happened, and come back — without judging yourself for it.",
          "options": [
            {
              "label": "Notice and return, without self-criticism",
              "feedback": "Right.",
              "isCorrect": true
            },
            {
              "label": "Try harder to stop it from happening again",
              "feedback": "That treats wandering as a failure — it's actually the practice working as designed.",
              "isCorrect": false
            }
          ]
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l39-l39-e1",
    "node_source_id": "stress-steady-under-pressure-l39",
    "order_index": 0,
    "type": "concept_card",
    "phase": "teach",
    "duration_seconds": 35,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": "exercise_as_stress_buffer",
    "content": {
      "title": "The Discharge The Zebra Gets For Free",
      "variant": "myth",
      "myth": "Exercise only helps mood in general — it doesn't do anything specific for stress reactivity.",
      "reality": "Movement done AHEAD of time measurably blunts your body's reaction to the NEXT stressor — it's the physical discharge the response was built for. Size it to what your body can already do today; anyone with a medical condition or who hasn't been active recently should keep it gentle and check with a clinician before increasing intensity. A ten-minute walk is the reference, not a workout."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l39-l39-e2",
    "node_source_id": "stress-steady-under-pressure-l39",
    "order_index": 1,
    "type": "intuition_check",
    "phase": "practice",
    "duration_seconds": 25,
    "scaffold_level": 2,
    "difficulty": 0.21,
    "is_scored": true,
    "concept": "exercise_as_stress_buffer",
    "content": {
      "prompt": "Does exercise work best done DURING an active stressor, to fix it in the moment?",
      "options": [
        {
          "id": "no",
          "label": "No — it works by changing reactivity to what comes NEXT"
        },
        {
          "id": "yes",
          "label": "Yes — exercising during a stressor resolves it"
        }
      ],
      "bestOptionId": "no",
      "reveal": "A walk this morning doesn't fix this afternoon's hard meeting while it's happening — it changes how hard your body reacts to it, before it even starts."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l39-l39-e3",
    "node_source_id": "stress-steady-under-pressure-l39",
    "order_index": 2,
    "type": "why_it_matters",
    "phase": "close",
    "duration_seconds": 30,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "The Ending Modern Life Skips",
      "instruction": "Read, then move on.",
      "message": "A zebra's chase resolves and physically discharges the mobilization for free. A deadline doesn't.",
      "explanation": "Movement is how you build that missing discharge back in, deliberately, ahead of the next stressor."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l40-l40-e1",
    "node_source_id": "stress-steady-under-pressure-l40",
    "order_index": 0,
    "type": "reframe_builder",
    "phase": "review",
    "duration_seconds": 50,
    "scaffold_level": 5,
    "difficulty": 0.54,
    "is_scored": true,
    "concept": "progressive_muscle_relaxation",
    "content": {
      "title": "The Contrast, Once More",
      "instruction": "Choose one phrase at a time.",
      "hotThought": "My lower back feels tight, but I've never thought to actually tense it on purpose to release it.",
      "trays": [
        {
          "id": "skill",
          "slotLabel": "The skill",
          "options": [
            {
              "id": "contrast",
              "label": "Tense on purpose, then release completely"
            },
            {
              "id": "avoid",
              "label": "Avoid moving it until it feels better on its own"
            }
          ]
        },
        {
          "id": "so",
          "slotLabel": "So",
          "options": [
            {
              "id": "notice",
              "label": "you learn what release actually feels like there too"
            },
            {
              "id": "nothing",
              "label": "nothing changes either way"
            }
          ]
        }
      ],
      "joinStrategy": {
        "type": "template",
        "template": "{skill} — {so}."
      },
      "comparisonFeedback": "The contrast principle works on any muscle group, not just the ones already practiced."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l40-l40-e2",
    "node_source_id": "stress-steady-under-pressure-l40",
    "order_index": 1,
    "type": "intuition_check",
    "phase": "review",
    "duration_seconds": 25,
    "scaffold_level": 2,
    "difficulty": 0.21,
    "is_scored": true,
    "concept": "exercise_as_stress_buffer",
    "content": {
      "prompt": "A walk this morning — what does it change about this afternoon's hard meeting?",
      "options": [
        {
          "id": "reactivity",
          "label": "How hard your body reacts to it"
        },
        {
          "id": "content",
          "label": "What actually happens in the meeting"
        }
      ],
      "bestOptionId": "reactivity",
      "reveal": "It changes your body's reactivity to the stressor, not the stressor itself."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l40-l40-e3",
    "node_source_id": "stress-steady-under-pressure-l40",
    "order_index": 2,
    "type": "guided_discovery_trail",
    "phase": "apply",
    "duration_seconds": 50,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": true,
    "concept": "exercise_as_stress_buffer",
    "content": {
      "title": "Size It Down",
      "instruction": "Answer each question in order.",
      "questions": [
        {
          "id": "q1",
          "prompt": "What's the biggest version of 'exercise' you're picturing right now?",
          "hint": "Notice if it's an all-or-nothing standard."
        },
        {
          "id": "q2",
          "prompt": "What's the smallest version that still counts as movement today?",
          "hint": "A ten-minute walk is the reference the research actually used."
        },
        {
          "id": "q3",
          "prompt": "When today could that smallest version actually happen?",
          "hint": "Name a real time, not 'sometime today'."
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l41-l41-e1",
    "node_source_id": "stress-steady-under-pressure-l41",
    "order_index": 0,
    "type": "invent_first",
    "phase": "review",
    "duration_seconds": 50,
    "scaffold_level": 6,
    "difficulty": 0.65,
    "is_scored": true,
    "concept": "slow_breathing_general",
    "content": {
      "title": "New Pattern, Same Lever",
      "instruction": "Read the case, then decide.",
      "question": "A yoga instructor teaches 'ocean breath' — a long, audible exhale through a slightly closed throat. Does this count as the same lever taught in this course?",
      "cases": [
        {
          "id": "case1",
          "name": "Ocean breath",
          "text": "A long, audible exhale through a slightly closed throat.",
          "label": "The Case"
        }
      ],
      "options": [
        {
          "id": "yes",
          "label": "Yes — a slow pace with a real, extended exhale"
        },
        {
          "id": "no",
          "label": "No — it wasn't one of the named patterns in this course"
        }
      ],
      "feedbackMap": {
        "yes": {
          "title": "Right",
          "body": "An extended, controlled exhale is exactly the mechanism — the specific name or technique origin doesn't matter.",
          "chain": [
            "The exhale here is deliberately extended.",
            "That's the exhale-vagus mechanism.",
            "It qualifies, regardless of its name."
          ]
        },
        "no": {
          "title": "Not quite",
          "body": "The mechanism generalizes to any pattern with a slow pace and a real exhale — it isn't limited to two named techniques.",
          "chain": [
            "Recognizing the mechanism matters more than recognizing the name."
          ],
          "counterTitle": "Try the mechanism angle",
          "counterBody": "Ask whether the exhale here is meaningfully extended, regardless of what it's called."
        }
      }
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l41-l41-e2",
    "node_source_id": "stress-steady-under-pressure-l41",
    "order_index": 1,
    "type": "reframe_builder",
    "phase": "review",
    "duration_seconds": 50,
    "scaffold_level": 5,
    "difficulty": 0.54,
    "is_scored": true,
    "concept": "mindful_noticing",
    "content": {
      "title": "Notice And Return, Again",
      "instruction": "Choose one phrase at a time.",
      "hotThought": "I keep losing focus during this walk, thinking about tomorrow's meeting instead of the walk itself — I'm bad at this.",
      "trays": [
        {
          "id": "reframe",
          "slotLabel": "What's actually happening",
          "options": [
            {
              "id": "normal",
              "label": "A normal wander — noticing it is the successful rep"
            },
            {
              "id": "failing",
              "label": "Evidence of being bad at mindfulness"
            }
          ]
        },
        {
          "id": "next",
          "slotLabel": "Next",
          "options": [
            {
              "id": "return",
              "label": "gently come back to the walk, no scorekeeping"
            },
            {
              "id": "quit",
              "label": "give up on the walk since it's not working"
            }
          ]
        }
      ],
      "joinStrategy": {
        "type": "template",
        "template": "{reframe} — {next}."
      },
      "comparisonFeedback": "The wandering itself was never the problem — noticing and returning, without judgment, is the whole skill."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l41-l41-e3",
    "node_source_id": "stress-steady-under-pressure-l41",
    "order_index": 2,
    "type": "toolkit_shelf",
    "phase": "practice",
    "duration_seconds": 35,
    "scaffold_level": 3,
    "difficulty": 0.32,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Your Body Toolkit",
      "instruction": "Tap a moment, then see which tool fits it.",
      "tools": [
        {
          "label": "Cyclic sighing",
          "use": "Fast-acting — for when you just need calm, right now."
        },
        {
          "label": "Box breathing",
          "use": "For a wait that needs a countable structure."
        },
        {
          "label": "Progressive muscle relaxation",
          "use": "For tension you can feel but haven't released."
        },
        {
          "label": "Mindful noticing",
          "use": "For a wandering mind, or checking in on your own state."
        },
        {
          "label": "Movement",
          "use": "Done ahead of time — buffers reactivity to what's coming."
        }
      ],
      "moments": [
        {
          "label": "Racing thoughts right now, need calm fast",
          "key": "racing",
          "response": "This is what cyclic sighing is for — no equipment, no setup.",
          "toolIndex": 0
        },
        {
          "label": "Waiting outside a room you don't want to walk into",
          "key": "waiting",
          "response": "A countable structure gives your attention somewhere to go.",
          "toolIndex": 1
        },
        {
          "label": "Body wound tight after sitting all day",
          "key": "tight",
          "response": "The tense-release contrast finds what you've been holding.",
          "toolIndex": 2
        },
        {
          "label": "Mind won't settle before trying to sleep",
          "key": "wandering",
          "response": "Notice the wander, come back, no scorekeeping.",
          "toolIndex": 3
        },
        {
          "label": "A demanding week ahead, want to be ready for it",
          "key": "ahead",
          "response": "A walk today changes how hard tomorrow's stressor lands.",
          "toolIndex": 4
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l42-l42-e1",
    "node_source_id": "stress-steady-under-pressure-l42",
    "order_index": 0,
    "type": "fill_blank",
    "phase": "review",
    "duration_seconds": 30,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": true,
    "concept": "exercise_as_stress_buffer",
    "content": {
      "title": "Buffering, Again",
      "instruction": "Fill in the blank.",
      "variants": [
        {
          "pre": "Exercise done ahead of time changes how hard your body ___",
          "post": " to the next stressor — it doesn't fix a stressor already in progress.",
          "answers": [
            "reacts"
          ],
          "correctFeedback": "Right — it's a buffering effect on reactivity, not an in-the-moment fix.",
          "incorrectFeedback": "It changes reactivity to the next stressor, not the current one.",
          "workedExample": "A walk this morning changes how hard this afternoon's meeting lands."
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l42-l42-e2",
    "node_source_id": "stress-steady-under-pressure-l42",
    "order_index": 1,
    "type": "invent_first",
    "phase": "apply",
    "duration_seconds": 50,
    "scaffold_level": 6,
    "difficulty": 0.65,
    "is_scored": true,
    "concept": null,
    "content": {
      "title": "Five Fresh Moments",
      "instruction": "Read the case, then pick the best-fit tool.",
      "question": "A tense shoulder and a racing mind, both at once, right before a call in two minutes — which tool fits best, given the time you actually have?",
      "cases": [
        {
          "id": "case1",
          "name": "Two minutes",
          "text": "Tense shoulder and racing mind, call starting in two minutes.",
          "label": "The Case"
        }
      ],
      "options": [
        {
          "id": "breath",
          "label": "A quick cyclic sigh — fast, no equipment, fits the two minutes"
        },
        {
          "id": "pmr",
          "label": "A full PMR body scan — thorough, but takes longer than two minutes"
        }
      ],
      "feedbackMap": {
        "breath": {
          "title": "Right",
          "body": "With only two minutes, the fastest-acting tool that needs no setup is the best fit — even though PMR would also help, it doesn't fit the time available.",
          "chain": [
            "Only two minutes available.",
            "Breath is the fastest lever with no setup.",
            "Best fit for THIS moment's constraint."
          ]
        },
        "pmr": {
          "title": "Not quite",
          "body": "PMR is a real tool, but a full scan doesn't fit inside two minutes — the time constraint itself is part of choosing well.",
          "chain": [
            "Time available is a real constraint on tool choice."
          ],
          "counterTitle": "Try the time-constraint angle",
          "counterBody": "Ask which tool actually fits inside two minutes."
        }
      }
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l43-l43-e1",
    "node_source_id": "stress-steady-under-pressure-l43",
    "order_index": 0,
    "type": "reframe_builder",
    "phase": "practice",
    "duration_seconds": 50,
    "scaffold_level": 5,
    "difficulty": 0.54,
    "is_scored": true,
    "concept": "acute_stress_response",
    "content": {
      "title": "Fast Or Slow — And Now, Which Tool",
      "instruction": "Choose one phrase at a time.",
      "hotThought": "A lingering, keyed-up feeling an hour after a hard call — is a body tool even still useful this late?",
      "trays": [
        {
          "id": "layer",
          "slotLabel": "Which layer",
          "options": [
            {
              "id": "hpa",
              "label": "HPA — the slower wave, still clearing"
            },
            {
              "id": "gone",
              "label": "Neither — this shouldn't still be happening"
            }
          ]
        },
        {
          "id": "tool",
          "slotLabel": "So which tool still helps",
          "options": [
            {
              "id": "breath-or-pmr",
              "label": "A breath or PMR — body-level tools help while HPA is still clearing"
            },
            {
              "id": "none",
              "label": "None — nothing helps once the jolt has passed"
            }
          ]
        }
      ],
      "joinStrategy": {
        "type": "template",
        "template": "This is the {layer} layer — {tool}."
      },
      "comparisonFeedback": "A body-level tool still helps while the slower HPA wave is clearing — it doesn't only work in the first few seconds."
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l43-l43-e2",
    "node_source_id": "stress-steady-under-pressure-l43",
    "order_index": 1,
    "type": "teach_back_chain",
    "phase": "practice",
    "duration_seconds": 55,
    "scaffold_level": 5,
    "difficulty": 0.54,
    "is_scored": true,
    "concept": "stress_signature",
    "content": {
      "title": "Your Tell, Your Tool",
      "instruction": "Order the sequence, then apply it to your own tell.",
      "message": "The tells aren't just for self-awareness — they're the trigger for which lever to reach for.",
      "steps": [
        {
          "id": "notice",
          "label": "Notice a body/thought/behavior tell",
          "order": 1
        },
        {
          "id": "channel",
          "label": "Identify which channel it's in",
          "order": 2
        },
        {
          "id": "match",
          "label": "Match the channel to the most direct tool",
          "order": 3
        }
      ],
      "transfer": {
        "prompt": "A tight jaw (a body-channel tell) — which tool is the most direct match?",
        "options": [
          {
            "id": "body-tool",
            "label": "A body-channel tool — breath or PMR",
            "isSupported": true,
            "response": "Right — a body-channel tell points most directly to a body-channel tool, faster than trying to think your way out first.",
            "takeaway": "Matching the channel is faster than defaulting to whichever tool comes to mind first."
          },
          {
            "id": "unrelated",
            "label": "Any tool — the channel doesn't matter",
            "isSupported": false,
            "response": "Not quite — a body-channel tell points most directly to a body-channel tool.",
            "takeaway": "The channel a tell shows up in is a real clue, not incidental."
          }
        ]
      }
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l44-l44-e1",
    "node_source_id": "stress-steady-under-pressure-l44",
    "order_index": 0,
    "type": "fill_blank",
    "phase": "review",
    "duration_seconds": 30,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": true,
    "concept": "exercise_as_stress_buffer",
    "content": {
      "title": "Buffering, Once More",
      "instruction": "Fill in the blank.",
      "variants": [
        {
          "pre": "Exercise done beforehand changes how hard your body reacts to the ___ stressor,",
          "post": " not the one already happening.",
          "answers": [
            "next"
          ],
          "correctFeedback": "Right — a buffering effect on the next stressor.",
          "incorrectFeedback": "It buffers the next stressor, not the current one.",
          "workedExample": "A morning walk changes how the afternoon meeting lands, not the meeting itself."
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l44-l44-e2",
    "node_source_id": "stress-steady-under-pressure-l44",
    "order_index": 1,
    "type": "guided_recall_chips",
    "phase": "review",
    "duration_seconds": 35,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": true,
    "concept": null,
    "content": {
      "title": "Two Mechanisms, Rebuilt",
      "instruction": "Tap the chips in order to rebuild both rules.",
      "prompt": "Slow breathing works through the ___ reaching the vagus; PMR works through the tense-release ___.",
      "chips": [
        "exhale",
        "contrast",
        "inhale",
        "breath"
      ],
      "answer": [
        "exhale",
        "contrast"
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l44-l44-e3",
    "node_source_id": "stress-steady-under-pressure-l44",
    "order_index": 2,
    "type": "teach_back_chain",
    "phase": "review",
    "duration_seconds": 55,
    "scaffold_level": 5,
    "difficulty": 0.54,
    "is_scored": true,
    "concept": null,
    "content": {
      "title": "Noticing And Buffering, Together",
      "instruction": "Order the sequence, then apply it.",
      "message": "Noticing early is what makes buffering deliberate rather than accidental.",
      "steps": [
        {
          "id": "notice",
          "label": "Notice attention wandering, or a tell showing up",
          "order": 1
        },
        {
          "id": "return",
          "label": "Return without judgment",
          "order": 2
        },
        {
          "id": "buffer",
          "label": "A walk earlier today already changed how this lands",
          "order": 3
        }
      ],
      "transfer": {
        "prompt": "Someone notices they're unusually irritable mid-afternoon, and remembers they walked this morning. What does the walk actually explain here?",
        "options": [
          {
            "id": "reactivity",
            "label": "Without it, this same trigger might have landed harder",
            "isSupported": true,
            "response": "Right — the walk buffered reactivity; it doesn't mean nothing can still trigger irritability, just that it likely lands somewhat softer.",
            "takeaway": "Buffering is a real but modest effect, not immunity."
          },
          {
            "id": "immune",
            "label": "The walk should have made them immune to irritability today",
            "isSupported": false,
            "response": "Not quite — buffering is a modest, real effect, not immunity from stress reactions.",
            "takeaway": "Don't overclaim what a buffering effect actually guarantees."
          }
        ]
      }
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l44-l44-e4",
    "node_source_id": "stress-steady-under-pressure-l44",
    "order_index": 3,
    "type": "invent_first",
    "phase": "review",
    "duration_seconds": 50,
    "scaffold_level": 6,
    "difficulty": 0.65,
    "is_scored": true,
    "concept": null,
    "content": {
      "title": "A Fresh Moment, Full Toolkit",
      "instruction": "Read the case, then choose.",
      "question": "A big presentation is two days out. What's the single best use of everything in Section 2, starting today?",
      "cases": [
        {
          "id": "case1",
          "name": "Two days out",
          "text": "A big presentation is two days out.",
          "label": "The Case"
        }
      ],
      "options": [
        {
          "id": "buffer-now",
          "label": "Movement today to buffer reactivity, plus a body tool ready for right before the presentation itself"
        },
        {
          "id": "wait",
          "label": "Save every tool for the moment right before the presentation"
        }
      ],
      "feedbackMap": {
        "buffer-now": {
          "title": "Right",
          "body": "This uses the toolkit as designed — movement done ahead buffers reactivity, and a fast body-channel tool is kept in reserve for the moment itself.",
          "chain": [
            "Movement's effect is about ahead-of-time buffering, not in-the-moment fixing.",
            "A breath or PMR check is still available right before.",
            "Both roles, used at the right time."
          ]
        },
        "wait": {
          "title": "Not quite",
          "body": "Movement's buffering effect specifically works when it's done AHEAD of the stressor — saving it for right before misses that window entirely.",
          "chain": [
            "Exercise as stress buffer requires advance timing, not last-minute use."
          ],
          "counterTitle": "Try the timing angle",
          "counterBody": "Ask which Section 2 tool specifically needs to happen ahead of time, not in the moment."
        }
      }
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l44-l44-e5",
    "node_source_id": "stress-steady-under-pressure-l44",
    "order_index": 4,
    "type": "course_checkpoint",
    "phase": "checkpoint",
    "duration_seconds": 50,
    "scaffold_level": 4,
    "difficulty": 0.43,
    "is_scored": false,
    "concept": null,
    "content": {
      "title": "Calming Your Body — Section Checkpoint",
      "introTitle": "Let's see what's solid.",
      "intro": "Four quick checks across all of Section 2.\nA miss just gives you something to revisit.",
      "introTag": "4 QUESTIONS · ~1 MIN",
      "revisitMessage": "The marked ideas are worth a short revisit — nothing is lost, and they'll come back around.",
      "solidMessage": "The body toolkit is holding. Next: giving the response an actual end.",
      "items": [
        {
          "concept": "Slow Breathing (General Mechanism)",
          "prompt": "What's the active ingredient in any slow breathing pattern?",
          "clue": "Not the count.",
          "worked": "A slow pace with a longer exhale, reaching the vagus nerve.",
          "options": [
            {
              "label": "A slow pace with a longer exhale",
              "feedback": "Right.",
              "isCorrect": true
            },
            {
              "label": "Matching a specific named technique exactly",
              "feedback": "The mechanism generalizes beyond any two named patterns.",
              "isCorrect": false
            }
          ]
        },
        {
          "concept": "Progressive Muscle Relaxation",
          "prompt": "What's PMR's actual skill?",
          "clue": "Not just relaxing.",
          "worked": "Noticing the contrast between tensed and released.",
          "options": [
            {
              "label": "Noticing the tense-release contrast",
              "feedback": "Right.",
              "isCorrect": true
            },
            {
              "label": "Staying relaxed at all times",
              "feedback": "The skill is the contrast, not constant relaxation.",
              "isCorrect": false
            }
          ]
        },
        {
          "concept": "Mindful Noticing",
          "prompt": "What should happen when attention wanders?",
          "clue": "No scorekeeping.",
          "worked": "Notice it, return, without self-criticism.",
          "options": [
            {
              "label": "Notice and return, without judgment",
              "feedback": "Right.",
              "isCorrect": true
            },
            {
              "label": "Try harder to prevent wandering",
              "feedback": "Wandering isn't the failure — the return is the skill.",
              "isCorrect": false
            }
          ]
        },
        {
          "concept": "Exercise as Stress Buffer",
          "prompt": "When does exercise's stress-buffering effect apply?",
          "clue": "Timing matters.",
          "worked": "Done ahead of a stressor, changing reactivity to what comes next.",
          "options": [
            {
              "label": "Done beforehand, buffering the next stressor",
              "feedback": "Right.",
              "isCorrect": true
            },
            {
              "label": "Done during an active stressor, to fix it",
              "feedback": "The buffering effect is about advance timing, not in-the-moment fixing.",
              "isCorrect": false
            }
          ]
        }
      ]
    }
  },
  {
    "source_id": "stress-steady-under-pressure-l44-l44-e6",
    "node_source_id": "stress-steady-under-pressure-l44",
    "order_index": 5,
    "type": "section_milestone",
    "phase": "checkpoint",
    "duration_seconds": 25,
    "scaffold_level": 1,
    "difficulty": 0.1,
    "is_scored": false,
    "concept": null,
    "content": {
      "badge": "Steady Hands",
      "closedTitle": "Section 2 Complete",
      "closedBody": "Tap to see what you've earned.",
      "openTitle": "You Can Reach The Brake Directly Now",
      "openBody": "You can now reach the brake directly with breath, body, or movement — matched to the moment, not just known in theory.",
      "nextLabel": "Next up:",
      "nextTitle": "Making It Last",
      "nextBody": "is about giving the response an actual end — recovery, sleep, support, boundaries — and rehearsing what you keep before the course ends."
    }
  }
]$tag$::jsonb) AS r(
  source_id text, node_source_id text, order_index int, type text, phase text, duration_seconds int,
  scaffold_level int, difficulty numeric, is_scored boolean, concept text, content jsonb
)
ON CONFLICT (id) DO UPDATE SET node_id = EXCLUDED.node_id, order_index = EXCLUDED.order_index, type = EXCLUDED.type, phase = EXCLUDED.phase, duration_seconds = EXCLUDED.duration_seconds, scaffold_level = EXCLUDED.scaffold_level, difficulty = EXCLUDED.difficulty, is_scored = EXCLUDED.is_scored, concept = EXCLUDED.concept, content = EXCLUDED.content;

DO $validation$
DECLARE
  expected_nodes INT := 18;
  expected_exercises INT := 57;
  actual_nodes INT;
  actual_exercises INT;
BEGIN
  SELECT count(*) INTO actual_nodes FROM nodes WHERE unit_id IN (SELECT pg_temp.seed_uuid(u.source_id) FROM jsonb_to_recordset($tag$[
  {
    "source_id": "stress-steady-under-pressure-s2-u1",
    "section_source_id": "stress-steady-under-pressure-s2",
    "title": "Breathing as a Direct Lever",
    "icon_key": "default",
    "order_index": 0
  },
  {
    "source_id": "stress-steady-under-pressure-s2-u2",
    "section_source_id": "stress-steady-under-pressure-s2",
    "title": "Releasing the Body's Tension",
    "icon_key": "default",
    "order_index": 1
  },
  {
    "source_id": "stress-steady-under-pressure-s2-u3",
    "section_source_id": "stress-steady-under-pressure-s2",
    "title": "Movement and Your Whole Toolkit",
    "icon_key": "default",
    "order_index": 2
  }
]$tag$::jsonb) AS u(source_id text, section_source_id text, title text, icon_key text, order_index int));
  SELECT count(*) INTO actual_exercises FROM exercises WHERE node_id IN (SELECT pg_temp.seed_uuid(n.source_id) FROM jsonb_to_recordset($tag$[
  {
    "source_id": "stress-steady-under-pressure-l27",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Why Slow Breathing Works At All",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 0,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l28",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Practice: Five Minutes, Five Days",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 1,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l29",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Box Breathing, In Practice",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 2,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l30",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Which Breath, Which Moment",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 3,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l31",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Breath Under Real Pressure",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 4,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l32",
    "unit_source_id": "stress-steady-under-pressure-s2-u1",
    "title": "Unit Checkpoint: Breath as a Tool",
    "type": "checkpoint",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 5,
    "estimated_mins": 3,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l33",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "Tense, Then Notice the Release",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 0,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l34",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "Noticing Without Fixing",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 1,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l35",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "When Your Mind Wanders, That's the Practice",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 2,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l36",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "A Body Scan in Three Zones",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 3,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l37",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "Tension You Didn't Notice You Were Holding",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 4,
    "estimated_mins": 1,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l38",
    "unit_source_id": "stress-steady-under-pressure-s2-u2",
    "title": "Unit Checkpoint: Release and Notice",
    "type": "checkpoint",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 5,
    "estimated_mins": 3,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l39",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Finish the Mobilization: Move",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 0,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l40",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Ten Minutes Counts",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 1,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l41",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Build Your Body Toolkit",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 2,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l42",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Which Tool, Which Moment (Review)",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 3,
    "estimated_mins": 1,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l43",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Your Body's Signals, Revisited",
    "type": "lesson",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 4,
    "estimated_mins": 2,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  },
  {
    "source_id": "stress-steady-under-pressure-l44",
    "unit_source_id": "stress-steady-under-pressure-s2-u3",
    "title": "Section 2 Checkpoint",
    "type": "checkpoint",
    "content_id": null,
    "content_type": null,
    "pass_threshold": null,
    "order_index": 5,
    "estimated_mins": 4,
    "icon": null,
    "new_concepts": [],
    "review_concepts": [],
    "prerequisites": []
  }
]$tag$::jsonb) AS n(source_id text, unit_source_id text, title text, type text, content_id text, content_type text, pass_threshold int, order_index int, estimated_mins int, icon text, new_concepts jsonb, review_concepts jsonb, prerequisites jsonb));
  IF actual_nodes != expected_nodes THEN
    RAISE EXCEPTION 'expected % nodes for this seed, found %', expected_nodes, actual_nodes;
  END IF;
  IF actual_exercises != expected_exercises THEN
    RAISE EXCEPTION 'expected % exercises for this seed, found %', expected_exercises, actual_exercises;
  END IF;
END $validation$;

COMMIT;
