import { StyleSheet } from "react-native";
import {
  COURSE_EXERCISE_FONTS,
  SEMANTIC_COLORS } from "@/src/components/exercise/courseExerciseTheme";

export const explorableModelStyles = StyleSheet.create({
  screen: {
    flex: 1,
    gap: 14,
    paddingHorizontal: 10,
    paddingBottom: 12,
    paddingTop: 6,
  },
  setup: {
    color: SEMANTIC_COLORS.text.secondary,
    fontFamily: COURSE_EXERCISE_FONTS.body,
    fontSize: 14,
    lineHeight: 20,
  },
  chart: {
    borderRadius: 16,
    paddingHorizontal: 6,
    paddingTop: 6,
    backgroundColor: SEMANTIC_COLORS.surface.secondary,
  },
  delta: {
    minHeight: 48,
    justifyContent: "center",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: SEMANTIC_COLORS.brand.soft,
  },
  deltaText: {
    color: SEMANTIC_COLORS.text.primary,
    fontFamily: COURSE_EXERCISE_FONTS.bodyMedium,
    fontSize: 14,
    lineHeight: 20,
  },
  control: { gap: 6 },
  controlHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  controlLabel: {
    color: SEMANTIC_COLORS.text.primary,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 14,
  },
  controlValue: {
    color: SEMANTIC_COLORS.brand.pressed,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 14,
  },
  slider: { width: "100%", height: 48 },
  toggle: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderWidth: 1.5,
    borderBottomWidth: 3,
    borderColor: SEMANTIC_COLORS.border.default,
    borderRadius: 16,
    paddingHorizontal: 16,
    backgroundColor: SEMANTIC_COLORS.surface.primary,
  },
  toggleActive: {
    borderColor: SEMANTIC_COLORS.brand.primary,
    backgroundColor: SEMANTIC_COLORS.brand.primary,
  },
  toggleLabel: {
    flex: 1,
    color: SEMANTIC_COLORS.text.primary,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 14,
  },
  toggleValue: {
    color: SEMANTIC_COLORS.text.secondary,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 13,
  },
  toggleLabelActive: { color: SEMANTIC_COLORS.surface.primary },
  complete: { gap: 10 },
  completeText: {
    color: SEMANTIC_COLORS.brand.pressed,
    fontFamily: COURSE_EXERCISE_FONTS.heading,
    fontSize: 22,
    lineHeight: 28,
  },
  inlineAction: {
    minHeight: 48,
    alignSelf: "flex-start",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: SEMANTIC_COLORS.brand.primary,
    borderRadius: 999,
    paddingHorizontal: 18,
    backgroundColor: SEMANTIC_COLORS.surface.primary,
  },
  inlineActionText: {
    color: SEMANTIC_COLORS.brand.pressed,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 14,
  },
  sandbox: { gap: 14 },
  sandboxControls: { gap: 10 },
  reset: {
    minHeight: 48,
    alignSelf: "flex-start",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  resetText: {
    color: SEMANTIC_COLORS.brand.pressed,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 14,
  },
  pressed: { opacity: 0.65, transform: [{ translateY: 1 }] },
});
