import { StyleSheet } from "react-native";
import {
  COURSE_EXERCISE_COLORS,
  COURSE_EXERCISE_FONTS,
} from "@/src/components/exercise/courseExerciseTheme";

export const explorableModelStyles = StyleSheet.create({
  screenContent: {
    flex: 1,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 12,
  },
  storyCard: {
    marginBottom: 10,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 24,
    backgroundColor: COURSE_EXERCISE_COLORS.surface,
    shadowColor: COURSE_EXERCISE_COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  story: {
    color: COURSE_EXERCISE_COLORS.ink,
    fontFamily: COURSE_EXERCISE_FONTS.body,
    fontSize: 13,
    lineHeight: 20,
  },
  modelCard: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 8,
    borderRadius: 24,
    backgroundColor: COURSE_EXERCISE_COLORS.surface,
    shadowColor: COURSE_EXERCISE_COLORS.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 7,
  },
  loadHeading: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 8,
    paddingHorizontal: 4,
  },
  loadTitle: {
    color: COURSE_EXERCISE_COLORS.ink,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 13.5,
  },
  loadCaption: {
    color: COURSE_EXERCISE_COLORS.inkSoft,
    fontFamily: COURSE_EXERCISE_FONTS.body,
    fontSize: 11.5,
  },
  slider: { width: "100%", height: 40 },
  levers: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  lever: {
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderWidth: 1.5,
    borderColor: COURSE_EXERCISE_COLORS.border,
    borderBottomWidth: 3,
    borderRadius: 20,
    backgroundColor: COURSE_EXERCISE_COLORS.surface,
  },
  activeLever: {
    borderColor: COURSE_EXERCISE_COLORS.accent,
    backgroundColor: COURSE_EXERCISE_COLORS.accent,
  },
  leverText: {
    color: COURSE_EXERCISE_COLORS.inkSoft,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 12,
  },
  activeLeverText: { color: COURSE_EXERCISE_COLORS.surface },
  pressed: { opacity: 0.65, transform: [{ translateY: 1 }] },
  verdict: {
    marginTop: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderWidth: 1.5,
    borderRadius: 20,
  },
  positive: {
    borderColor: COURSE_EXERCISE_COLORS.accent,
    backgroundColor: COURSE_EXERCISE_COLORS.accentTint,
  },
  warning: {
    borderColor: COURSE_EXERCISE_COLORS.accentLight,
    backgroundColor: COURSE_EXERCISE_COLORS.accentTint,
  },
  verdictTitle: {
    marginBottom: 3,
    color: COURSE_EXERCISE_COLORS.ink,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 14.5,
  },
  verdictBody: {
    color: COURSE_EXERCISE_COLORS.inkSoft,
    fontFamily: COURSE_EXERCISE_FONTS.body,
    fontSize: 12.5,
    lineHeight: 19,
  },
  goals: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 10 },
  goal: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: COURSE_EXERCISE_COLORS.inkSoft,
    borderRadius: 18,
  },
  goalText: {
    color: COURSE_EXERCISE_COLORS.inkSoft,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 11.5,
  },
});
