import { StyleSheet } from "react-native";
import {
  COURSE_EXERCISE_COLORS,
  COURSE_EXERCISE_FONTS,
} from "@/src/components/exercise/courseExerciseTheme";

export const paradoxCardStyles = StyleSheet.create({
  screenContent: {
    flex: 1,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 12,
  },
  comparisonRow: { flexDirection: "row", gap: 8, marginBottom: 14 },
  comparisonCard: {
    flex: 1,
    minHeight: 124,
    paddingHorizontal: 13,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: COURSE_EXERCISE_COLORS.surface,
    shadowColor: COURSE_EXERCISE_COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  orangeCard: {
    borderWidth: 1.5,
    borderColor: COURSE_EXERCISE_COLORS.orangeLight,
    backgroundColor: COURSE_EXERCISE_COLORS.orangeTint,
    shadowOpacity: 0,
  },
  comparisonLabel: {
    marginBottom: 4,
    color: COURSE_EXERCISE_COLORS.oliveDark,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.45,
  },
  orangeLabel: { color: COURSE_EXERCISE_COLORS.orangeRim },
  comparisonBody: {
    color: COURSE_EXERCISE_COLORS.ink,
    fontFamily: COURSE_EXERCISE_FONTS.body,
    fontSize: 12.5,
    lineHeight: 19,
  },
  orangeBody: { color: COURSE_EXERCISE_COLORS.orangeRim },
  alarmLabels: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  alarmEdge: {
    color: COURSE_EXERCISE_COLORS.inkSoft,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 11.5,
  },
  alarmTitle: {
    color: COURSE_EXERCISE_COLORS.inkSoft,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 11.5,
    letterSpacing: 0.45,
  },
  alarmTrack: {
    height: 18,
    overflow: "hidden",
    marginTop: 4,
    marginBottom: 10,
    borderRadius: 999,
    backgroundColor: COURSE_EXERCISE_COLORS.surfaceMuted,
  },
  alarmFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: COURSE_EXERCISE_COLORS.orange,
  },
  caption: {
    minHeight: 61,
    marginBottom: 10,
    color: COURSE_EXERCISE_COLORS.ink,
    fontFamily: COURSE_EXERCISE_FONTS.body,
    fontSize: 13.5,
    lineHeight: 20,
  },
  actions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  pushButton: {
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderWidth: 1.5,
    borderBottomWidth: 4,
    borderColor: COURSE_EXERCISE_COLORS.orange,
    borderRadius: 23,
    backgroundColor: COURSE_EXERCISE_COLORS.orangeTint,
  },
  pushLabel: {
    color: COURSE_EXERCISE_COLORS.orangeRim,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 12.5,
    letterSpacing: 0.35,
  },
  stopButton: {
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderWidth: 1.5,
    borderBottomWidth: 4,
    borderColor: COURSE_EXERCISE_COLORS.border,
    borderRadius: 23,
    backgroundColor: COURSE_EXERCISE_COLORS.surface,
  },
  stopLabel: {
    color: COURSE_EXERCISE_COLORS.ink,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 13,
  },
  disabled: { opacity: 0.5, borderBottomWidth: 1 },
  pressed: { transform: [{ translateY: 2 }], borderBottomWidth: 2 },
  revealCard: {
    marginTop: 12,
    paddingHorizontal: 22,
    paddingVertical: 20,
    borderRadius: 28,
    backgroundColor: COURSE_EXERCISE_COLORS.surface,
    shadowColor: COURSE_EXERCISE_COLORS.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 7,
  },
  rule: {
    color: COURSE_EXERCISE_COLORS.oliveDark,
    fontFamily: COURSE_EXERCISE_FONTS.heading,
    fontSize: 19,
    lineHeight: 26,
  },
  takeaway: {
    marginTop: 6,
    color: COURSE_EXERCISE_COLORS.ink,
    fontFamily: COURSE_EXERCISE_FONTS.body,
    fontSize: 14,
    lineHeight: 22,
  },
});
