import { StyleSheet } from "react-native";
import {
  COURSE_EXERCISE_COLORS,
  COURSE_EXERCISE_FONTS,
} from "@/src/components/exercise/courseExerciseTheme";

export const storySerialStyles = StyleSheet.create({
  screenContent: {
    flex: 1,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 12,
  },
  openingCard: {
    marginBottom: 14,
    paddingHorizontal: 17,
    paddingVertical: 15,
    borderRadius: 24,
    borderBottomLeftRadius: 7,
    backgroundColor: COURSE_EXERCISE_COLORS.surface,
    shadowColor: COURSE_EXERCISE_COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  episodeLabel: {
    marginBottom: 5,
    color: COURSE_EXERCISE_COLORS.oliveDark,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 10.5,
    letterSpacing: 0.7,
  },
  opening: {
    color: COURSE_EXERCISE_COLORS.ink,
    fontFamily: COURSE_EXERCISE_FONTS.body,
    fontSize: 14.5,
    lineHeight: 22,
  },
  section: { gap: 9, marginTop: 4 },
  sectionLabel: {
    color: COURSE_EXERCISE_COLORS.inkSoft,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 10.5,
    letterSpacing: 0.65,
  },
  beatList: { gap: 9, marginTop: 9 },
  beat: {
    paddingHorizontal: 15,
    paddingVertical: 13,
    borderWidth: 1,
    borderColor: COURSE_EXERCISE_COLORS.border,
    borderRadius: 20,
    backgroundColor: COURSE_EXERCISE_COLORS.surface,
    shadowColor: COURSE_EXERCISE_COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  alternateBeat: {
    borderStyle: "dashed",
    borderColor: COURSE_EXERCISE_COLORS.olive,
    shadowOpacity: 0,
  },
  beatLabel: {
    marginBottom: 3,
    color: COURSE_EXERCISE_COLORS.orange,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 10,
    letterSpacing: 0.75,
  },
  alternateLabel: { color: COURSE_EXERCISE_COLORS.oliveDark },
  beatText: {
    color: COURSE_EXERCISE_COLORS.ink,
    fontFamily: COURSE_EXERCISE_FONTS.body,
    fontSize: 13.5,
    lineHeight: 21,
  },
  rewindButton: {
    minHeight: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    borderWidth: 1.5,
    borderColor: COURSE_EXERCISE_COLORS.orange,
    borderRadius: 24,
    backgroundColor: COURSE_EXERCISE_COLORS.orangeTint,
  },
  rewindLabel: {
    color: COURSE_EXERCISE_COLORS.orangeRim,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 14,
  },
  pressed: { opacity: 0.7, transform: [{ translateY: 1 }] },
  reflectionPrompt: {
    marginTop: 6,
    color: COURSE_EXERCISE_COLORS.ink,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 15,
    lineHeight: 22,
  },
  ending: { marginTop: 10 },
  coach: {
    marginHorizontal: 2,
    color: COURSE_EXERCISE_COLORS.inkSoft,
    fontFamily: COURSE_EXERCISE_FONTS.body,
    fontSize: 13,
    fontStyle: "italic",
    lineHeight: 20,
  },
  stamp: {
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: COURSE_EXERCISE_COLORS.olive,
    borderRadius: 20,
  },
  stampText: {
    color: COURSE_EXERCISE_COLORS.oliveDark,
    fontFamily: COURSE_EXERCISE_FONTS.heading,
    fontSize: 19,
    lineHeight: 25,
    textAlign: "center",
  },
  hook: {
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: COURSE_EXERCISE_COLORS.border,
    borderRadius: 20,
  },
  hookText: {
    color: COURSE_EXERCISE_COLORS.inkSoft,
    fontFamily: COURSE_EXERCISE_FONTS.bodyBold,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
});
