import { StyleSheet } from "react-native";
import { APP_FONT_FAMILIES } from "@/src/theme/typography";
import { SEMANTIC_COLORS } from "@/src/theme/colors";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: SEMANTIC_COLORS.border.default,
  },
  title: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 15,
    color: SEMANTIC_COLORS.text.primary,
    lineHeight: 20,
  },
  categoryPill: {
    backgroundColor: SEMANTIC_COLORS.selection.surface,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: "flex-start",
    marginTop: 4,
  },
  category: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 11,
    color: SEMANTIC_COLORS.brand.onSoft,
    lineHeight: 15,
  },
  cardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
  },
  badgeRow: { marginTop: 8 },
  timestamp: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 11,
    color: SEMANTIC_COLORS.text.secondary,
    letterSpacing: 0.2,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  headerTextContainer: { flex: 1, paddingRight: 8 },
  chevron: { marginTop: 4 },
  previewText: {
    fontFamily: APP_FONT_FAMILIES.regular,
    fontStyle: "italic",
    fontSize: 13,
    color: SEMANTIC_COLORS.text.secondary,
    marginTop: 8,
    lineHeight: 18,
  },
  expandedContent: {
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: SEMANTIC_COLORS.border.default,
    paddingTop: 12,
  },
  previewTextExpanded: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 14,
    color: SEMANTIC_COLORS.text.primary,
    marginBottom: 0,
    lineHeight: 20,
  },
  expandedText: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 14,
    color: SEMANTIC_COLORS.text.primary,
    lineHeight: 20,
  },
  tagsContainer: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 4 },
  tag: {
    backgroundColor: SEMANTIC_COLORS.brand.soft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  tagText: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 11,
    color: SEMANTIC_COLORS.brand.onSoft,
  },
  viewDetailsButton: { marginTop: 8, paddingVertical: 4, alignItems: "flex-start" },
  viewDetailsText: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 13,
    color: SEMANTIC_COLORS.brand.onSoft,
  },
  inlineTagsText: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 13,
    color: SEMANTIC_COLORS.text.secondary,
  },
  previewContainer: { marginBottom: 14 },
  sectionLabel: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 13,
    color: SEMANTIC_COLORS.text.secondary,
    marginBottom: 6,
  },
  previewLabel: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 14,
    color: SEMANTIC_COLORS.text.primary,
    marginBottom: 4,
  },
  emotionsContainer: { marginBottom: 14 },
  emotionBarRow: { flexDirection: "row", alignItems: "center", marginBottom: 6 },
  emotionText: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 12,
    color: SEMANTIC_COLORS.text.primary,
    width: 60,
  },
  emotionBarBg: {
    flex: 1,
    height: 6,
    backgroundColor: SEMANTIC_COLORS.brand.soft,
    borderRadius: 3,
    marginHorizontal: 8,
    overflow: "hidden",
  },
  emotionBarFill: { height: "100%", backgroundColor: SEMANTIC_COLORS.brand.primary, borderRadius: 3 },
  emotionIntensity: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 11,
    color: SEMANTIC_COLORS.text.tertiary,
    width: 24,
    textAlign: "right",
  },
  tagsSection: { marginTop: 4, marginBottom: 14 },
  gratitudeContainer: { marginBottom: 14, gap: 8 },
  gratitudeRow: { flexDirection: "row", alignItems: "flex-start" },
  gratitudeIcon: { marginTop: 2, marginRight: 8 },
  gratitudeText: {
    flex: 1,
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 13,
    color: SEMANTIC_COLORS.text.primary,
    lineHeight: 18,
  },
  balancedThoughtContainer: { marginBottom: 2 },
  reframeCard: {
    backgroundColor: SEMANTIC_COLORS.selection.surface,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 4,
    marginBottom: 10,
  },
  reframeHeader: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 6 },
  reframeLabel: {
    fontFamily: APP_FONT_FAMILIES.semiBold,
    fontSize: 12,
    color: SEMANTIC_COLORS.brand.onSoft,
  },
});
