-- Migration: public.journal_records table and indexes (No AI columns on journal_records)

CREATE TABLE IF NOT EXISTS public.journal_records (
  duration_seconds bigint null,
  transcripts text null,
  input_type text null,
  user_id uuid null default auth.uid (),
  title text null,
  selected_date timestamp with time zone null,
  id bigint generated by default as identity not null,
  is_bookmarked boolean null default false,
  bookmarked_at timestamp with time zone null,
  words_count integer null,
  constraint journal_records_pkey primary key (id),
  constraint journal_records_user_id_fkey foreign KEY (user_id) references profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_journal_records_user_selected_date on public.journal_records using btree (user_id, selected_date) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_journal_records_selected_date on public.journal_records using btree (selected_date) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_journal_records_user_id on public.journal_records using btree (user_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_journal_records_bookmarked on public.journal_records using btree (user_id, is_bookmarked, bookmarked_at desc) TABLESPACE pg_default
  where (is_bookmarked = true);

-- Allow journal_id in journal_ai to store bigint strings from journal_records.id
ALTER TABLE IF EXISTS public.journal_ai ALTER COLUMN journal_id TYPE text USING journal_id::text;

