import { GoogleGenAI } from "@google/genai";

export type FeelingsType = {
  name: string;
  emoji: string;
  colorsGradient: string[];
};

export type InsightsType = {
  moodScore?: number;
  suggestedTags?: string[];
  growthAreas?: string[];
  positiveInsights?: string[];
  summary?: string;
  mainEmoji?: string;
  feelings?: FeelingsType[];
  title?: string;
  enrichedTranscript?: string;
  aiInsights?: string;
  created_at?: string;
};

export const defaultInsights: InsightsType = {
  moodScore: 0,
  suggestedTags: [],
  growthAreas: [],
  positiveInsights: [],
  summary: "",
  mainEmoji: "",
  feelings: [],
  title: "",
  enrichedTranscript: "",
  aiInsights: "",
};
const ai = new GoogleGenAI({
  apiKey: "AIzaSyAx2xyv9nnK2-smi3YElqL48kQZQ8_EKBc",
});

export const getInsights = async (transcript: string) => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash",
      contents: `Here is a journal entry:\n\n${transcript}\n\n
      Analyze it and return insights in JSON format following the schema.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: "object",
          properties: {
            moodScore: {
              type: "integer",
              description:
                "Overall mood score between 1 (very negative) and 5 (very positive).",
            },
            suggestedTags: {
              type: "array",
              items: { type: "string" },
              description: "Keywords/tags that categorize this entry.",
            },
            growthAreas: {
              type: "array",
              items: { type: "string" },
              description:
                "Challenges, areas for self-reflection, or improvement.",
            },
            positiveInsights: {
              type: "array",
              items: { type: "string" },
              description:
                "Positive takeaways, gratitude points, or strengths.",
            },
            summary: {
              type: "string",
              description:
                "A short empathetic summary written directly to the user (e.g., 'You are feeling overwhelmed but also hopeful...').",
            },
            mainEmoji: {
              type: "string",
              enum: ["terrible", "bad", "fine", "good", "great"],
            },
            feelings: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  name: { type: "string" },
                  emoji: {
                    type: "string",
                    description: "Emoji representing the feeling.",
                  },
                  colorsGradient: {
                    type: "array",
                    items: {
                      type: "string",
                      description:
                        "Colors for the gradient background that represents the feeling of the tag chip. The first color is the top color and the second color is the bottom color.",
                    },
                  },
                },
                required: ["name", "emoji", "colorsGradient"],
              },
              description: "Different feelings expressed in the journal.",
            },
            title: {
              type: "string",
              description: "Add a short 'title' in a few words.",
            },
            enrichedTranscript: {
              type: "string",
              description:
                "The journal entry returned as a single string, but formatted with line breaks (\\n) between sentences or logical sections for readability, with emojis added where appropriate.",
            },
            aiInsights: {
              type: "string",
              description:
                "Deeper reflection generated by AI that highlights patterns, connections, or broader meaning behind the entry.",
            },
          },
          required: [
            "moodScore",
            "suggestedTags",
            "growthAreas",
            "positiveInsights",
            "summary",
            "mainEmoji",
            "feelings",
            "enrichedTranscript",
            "aiInsights",
          ],
        },
      },
    });

    if (!response.text) return defaultInsights;
    const insights: InsightsType = JSON.parse(response.text);
    return insights;
  } catch (error) {
    console.error("Error getting insights:", error);
    return defaultInsights;
  }
};

export type AIRecommendation = {
  title: string;
  description: string;
  category: 'mental_health' | 'productivity' | 'relationships' | 'self_care' | 'growth';
  actionSteps: string[];
  icon: string;
  priority: 'high' | 'medium' | 'low';
};

export type WeeklySummary = {
  weekStart: string;
  weekEnd: string;
  overallMood: number;
  moodTrend: 'improving' | 'stable' | 'declining';
  topEmotions: string[];
  keyHighlights: string[];
  growthAchievements: string[];
  areasOfConcern: string[];
  motivationalMessage: string;
  nextWeekFocus: string[];
  entriesCount: number;
  streakDays: number;
};

export type MonthlySummary = {
  month: string;
  year: number;
  overallMood: number;
  moodTrend: 'improving' | 'stable' | 'declining';
  topEmotions: string[];
  monthlyHighlights: string[];
  personalGrowth: string[];
  challenges: string[];
  achievements: string[];
  recommendation: string;
  nextMonthGoals: string[];
  entriesCount: number;
  consistencyScore: number;
};

export type GrowthInsight = {
  insight: string;
  category: string;
  supportingEvidence: string[];
  suggestion: string;
  impactLevel: 'high' | 'medium' | 'low';
};

/**
 * Generate personalized growth recommendations based on recent journal entries
 */
export const generateAIRecommendations = async (
  entries: Array<{
    enrichedTranscript: string;
    moodScore: number;
    feelings: any;
    created_at: string;
  }>
): Promise<AIRecommendation[]> => {
  try {
    if (!entries || entries.length === 0) {
      return [];
    }

    const entriesText = entries
      .map(
        (e, i) =>
          `Entry ${i + 1} (${e.created_at}):\nMood: ${e.moodScore}/5\n${e.enrichedTranscript}\n`
      )
      .join('\n---\n');

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: `Analyze these recent journal entries and provide personalized growth recommendations:\n\n${entriesText}\n\nGenerate 3-5 actionable recommendations.`,
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              title: { type: 'string' },
              description: { type: 'string' },
              category: {
                type: 'string',
                enum: ['mental_health', 'productivity', 'relationships', 'self_care', 'growth'],
              },
              actionSteps: {
                type: 'array',
                items: { type: 'string' },
              },
              icon: { type: 'string' },
              priority: {
                type: 'string',
                enum: ['high', 'medium', 'low'],
              },
            },
            required: ['title', 'description', 'category', 'actionSteps', 'icon', 'priority'],
          },
        },
      },
    });

    if (!response.text) return [];
    return JSON.parse(response.text);
  } catch (error) {
    console.error('Error generating recommendations:', error);
    return [];
  }
};

/**
 * Generate weekly summary from journal entries
 */
export const generateWeeklySummary = async (
  entries: Array<{
    enrichedTranscript: string;
    moodScore: number;
    feelings: any;
    created_at: string;
  }>,
  weekStart: string,
  weekEnd: string,
  streakDays: number
): Promise<WeeklySummary | null> => {
  try {
    if (!entries || entries.length === 0) {
      return null;
    }

    const entriesText = entries
      .map(
        (e, i) =>
          `Entry ${i + 1} (${e.created_at}):\nMood: ${e.moodScore}/5\n${e.enrichedTranscript}\n`
      )
      .join('\n---\n');

    const avgMood = entries.reduce((sum, e) => sum + (e.moodScore || 0), 0) / entries.length;

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: `Generate a weekly summary for the week of ${weekStart} to ${weekEnd}. The user made ${entries.length} entries with an average mood of ${avgMood.toFixed(1)}/5 and maintained a ${streakDays} day streak.\n\nEntries:\n${entriesText}`,
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: 'object',
          properties: {
            weekStart: { type: 'string' },
            weekEnd: { type: 'string' },
            overallMood: { type: 'number' },
            moodTrend: {
              type: 'string',
              enum: ['improving', 'stable', 'declining'],
            },
            topEmotions: {
              type: 'array',
              items: { type: 'string' },
            },
            keyHighlights: {
              type: 'array',
              items: { type: 'string' },
            },
            growthAchievements: {
              type: 'array',
              items: { type: 'string' },
            },
            areasOfConcern: {
              type: 'array',
              items: { type: 'string' },
            },
            motivationalMessage: { type: 'string' },
            nextWeekFocus: {
              type: 'array',
              items: { type: 'string' },
            },
            entriesCount: { type: 'integer' },
            streakDays: { type: 'integer' },
          },
          required: [
            'weekStart',
            'weekEnd',
            'overallMood',
            'moodTrend',
            'topEmotions',
            'keyHighlights',
            'motivationalMessage',
          ],
        },
      },
    });

    if (!response.text) return null;
    const summary = JSON.parse(response.text);
    return {
      ...summary,
      entriesCount: entries.length,
      streakDays,
    };
  } catch (error) {
    console.error('Error generating weekly summary:', error);
    return null;
  }
};

/**
 * Generate monthly summary
 */
export const generateMonthlySummary = async (
  entries: Array<{
    enrichedTranscript: string;
    moodScore: number;
    feelings: any;
    created_at: string;
  }>,
  month: string,
  year: number
): Promise<MonthlySummary | null> => {
  try {
    if (!entries || entries.length === 0) {
      return null;
    }

    const entriesText = entries
      .slice(0, 30)
      .map(
        (e, i) =>
          `Entry ${i + 1} (${e.created_at}):\nMood: ${e.moodScore}/5\n${e.enrichedTranscript?.substring(0, 200)}...\n`
      )
      .join('\n---\n');

    const avgMood = entries.reduce((sum, e) => sum + (e.moodScore || 0), 0) / entries.length;

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: `Generate a monthly summary for ${month} ${year}. The user made ${entries.length} entries with an average mood of ${avgMood.toFixed(1)}/5.\n\nSample entries:\n${entriesText}`,
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: 'object',
          properties: {
            month: { type: 'string' },
            year: { type: 'integer' },
            overallMood: { type: 'number' },
            moodTrend: {
              type: 'string',
              enum: ['improving', 'stable', 'declining'],
            },
            topEmotions: {
              type: 'array',
              items: { type: 'string' },
            },
            monthlyHighlights: {
              type: 'array',
              items: { type: 'string' },
            },
            personalGrowth: {
              type: 'array',
              items: { type: 'string' },
            },
            challenges: {
              type: 'array',
              items: { type: 'string' },
            },
            achievements: {
              type: 'array',
              items: { type: 'string' },
            },
            recommendation: { type: 'string' },
            nextMonthGoals: {
              type: 'array',
              items: { type: 'string' },
            },
            entriesCount: { type: 'integer' },
            consistencyScore: { type: 'number' },
          },
          required: [
            'month',
            'year',
            'overallMood',
            'moodTrend',
            'topEmotions',
            'monthlyHighlights',
            'recommendation',
          ],
        },
      },
    });

    if (!response.text) return null;
    const summary = JSON.parse(response.text);
    return {
      ...summary,
      entriesCount: entries.length,
    };
  } catch (error) {
    console.error('Error generating monthly summary:', error);
    return null;
  }
};

/**
 * Detect patterns and generate deep growth insights
 */
export const generateGrowthInsights = async (
  entries: Array<{
    enrichedTranscript: string;
    moodScore: number;
    feelings: any;
    created_at: string;
  }>
): Promise<GrowthInsight[]> => {
  try {
    if (!entries || entries.length < 5) {
      return [];
    }

    const entriesText = entries
      .slice(0, 20)
      .map(
        (e, i) =>
          `Entry ${i + 1} (${e.created_at}):\nMood: ${e.moodScore}/5\n${e.enrichedTranscript?.substring(0, 300)}...\n`
      )
      .join('\n---\n');

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: `Analyze these journal entries and identify deep patterns, recurring themes, and growth opportunities. Provide 3-5 actionable insights.\n\nEntries:\n${entriesText}`,
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              insight: { type: 'string' },
              category: { type: 'string' },
              supportingEvidence: {
                type: 'array',
                items: { type: 'string' },
              },
              suggestion: { type: 'string' },
              impactLevel: {
                type: 'string',
                enum: ['high', 'medium', 'low'],
              },
            },
            required: ['insight', 'category', 'supportingEvidence', 'suggestion', 'impactLevel'],
          },
        },
      },
    });

    if (!response.text) return [];
    return JSON.parse(response.text);
  } catch (error) {
    console.error('Error generating growth insights:', error);
    return [];
  }
};
